In [2]:
import pandas as pd

# Data Loading

In [5]:
questions = pd.read_csv('../data/raw/questions_clean.csv')

In [ ]:
data = pd.read_csv('../data/raw/websites_updated.csv')

# Mini sample for test

In [30]:
questions.sample(200).to_csv('../data/raw/questions_clean_sample_200.csv')

In [33]:
data.sample(200).to_csv('../data/raw/websites_updated_sample_200.csv')

# EDA

In [43]:
data.head(3)

,web_id,url,kind,title,text
0,1,https://alfabank.ru/,html,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,https://alfabank.ru/a-club/,html,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,https://alfabank.ru/a-club/ultimate/,html,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

In [44]:
questions.head()

   q_id                                                     query
0     1                                               Номер счета
1     2                                     Где узнать бик и счёт
2     3    Мне не приходят коды для подтверждения данной операции
3     4      Оформила рассрочку ,но уведомлений никаких не пришло
4     5  Здравствуйте, когда смогу пользоваться кредитной картой?

In [9]:
data.kind.value_counts()

kind
html        1802
document     135
Name: count, dtype: int64

In [46]:
data[data.kind=='document'].head(3)

      web_id  \
33        34
1487    1488
1703    1704

                                                                                                     url  \
33                         https://alfabank.servicecdn.ru/site-upload/5e/8b/1053/zalog_general_terms.pdf
1487                              https://alfabank.st/site-upload/38/95/1784/Refin-pamyatka-08022024.pdf
1703  https://alfabank.servicecdn.ru/site-upload/e3/30/1869/dogovor_cbo_1082025.pdf?previewDocument=true

          kind                        title  \
33    document      zalog_general_terms.pdf
1487  document  Refin-pamyatka-08022024.pdf
1703  document      dogovor_cbo_1082025.pdf


In [18]:
data.text.iloc[0]

'Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке'

# Extracting importance columns

In [47]:
data_clean = data[['web_id', 'title', 'text']]

In [49]:
data_clean.head(3)

,web_id,title,text
0,1,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

# Answer checking

In [6]:
ans = pd.read_csv('ans/questions_top5_web_ids.csv')

In [33]:
pd.set_option('display.max_colwidth', None)

In [37]:
for i in ans.values:
    print(i)
    print(questions[questions.q_id == i[0]]['query'])
    print(data[data.web_id == i[1]]['title'])
    print(data[data.web_id == i[1]]['text'])
    print()

[1136.  579.  468.  438. 1705. 1910.]
1135    Как скачать альфу на айфоне
Name: query, dtype: object
578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object
578    19.12.2024\nПодробнее: «Альфа‑Вклад»
Name: text, dtype: object

[2185.  860. 1620. 1677. 1746.   nan]
2184    Пропала кредитная карта из моего приложения
Name: query, dtype: object
859    Лучшее мобильное приложение
Name: title, dtype: object
859    Приложение Альфа-Банк в вашем смартфоне\nОтсканируйте QR-код камерой смартфона, перейдите по ссылке и следуйте инструкции.
Name: text, dtype: object

[6461. 1677.  628.  444.  579. 1694.]
6460    я не мгу нати раздел витрина
Name: query, dtype: object
1676    Услуга по накоплению «Копилка для зарплаты»💰
Name: title, dtype: object
1676    Любой процент отчисления\nМожно выбрать от 5% до 100% от каждой зарплаты.\nУдобное управление\nПодключить, отключить или изменить % можно в любой момент в приложении или позвонив специалисту банка.\nУслугу «Копилка для зарплаты» нельзя подключить к индивидуальной зарплатной карте, оформленной самостоятельно, не в рамках зарплатного проекта.\nВ рамках услуги «Копилка для зарплаты», подключенной до 20 июля 2020 года включительно, перечисления осуществляются на счёт «Накопилка». Для переключения услуги «Копилка для зарплаты» со счёта «Накопилка» на Альфа-Счёт, необходимо отключить услугу и подключить её заново.\nПри подключении услуги впервые — услуга автоматически подключается ко всем работодателям с одинаковыми параметрами;\nУслуга будет подключена автоматически при добавлении нового работодателя, от которого ранее вы не получали зарплату. Для него будут установлены параметры, соответствующие последней подключенной услуге, если сумма накопления была установлена как % от суммы заработной платы;\nПри изменении параметров хотя бы по одной услуге новый % будет применяться ко всем работодателям, включая компании, которые ранее не были подключены к услуге, либо по ним была установлена фиксированная сумма перевода.\nУслуга «Копилка для зарплаты» распространяется на все поступления на мой зарплатный счет?\nЯ не получаю заработную плату на карту Альфа‑Банка. Могу ли я подключить услугу «Копилка для зарплаты»?\nМогу ли я подключить услугу «Копилка для зарплаты», если я оформил индивидуальную зарплатную карту в Альфа-Банке?\nУ меня уже подключена услуга «Копилка для сдачи» с зачислением на счет «Накопилка». Могу ли я подключить услугу «Копилка для зарплаты»?\nКак быть, если в день поступления зарплаты, перевод средств на счет «Накопилка»/ «Альфа-Счёт» не был осуществлен?\nМожет ли указываемый процент от заработной платы быть не целым, а дробным?\nСкачайте PDF с подробными условиями\n173,7 Кб\n233,8 Кб\nУслуга «Копилка для зарплаты»
Name: text, dtype: object

[2490.  579. 1856. 1317.  578.  468.]
2489    Подключена
Name: query, dtype: object
578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object
578    19.12.2024\nПодробнее: «Альфа‑Вклад»
Name: text, dtype: object

[4383. 1694. 1746. 1677.  579.   nan]
4382    Где мой кэшбека за заправку на тебойл
Name: query, dtype: object
1693    Alfa Only – Кэшбэк до 20% в ЦУМе и ДЛТ — 🅰️ Альфа-Банк
Name: title, dtype: object
1693    Присоединяйтесь к Alfa Only и получите наши лучшие привилегии, а также эксклюзивные преимущества шопинга в ЦУМе и ДЛТ\n20% бонусами по картам ЦУМа и ДЛТ Black вместо 10%\n8% бонусами по картам ЦУМа и ДЛТ Orange вместо 5%\nБез ограничений максимальная сумма кэшбэка\nДля держателей карт лояльности ЦУМа и ДЛТ Orange и Black\nИ компенсация до 150 000 ₽ на кафе и рестораны в российских аэропортах\nИ ограничений по сумме\nПремиальный бизнес-зал для клиентов Alfa Only, где само ожидание вылета становится приятной частью путешествия\nКомплимент каждому гостю: фирменный коктейль или бокал игристого\nБар с авторскими напитками, шведский стол\nВсё для отдыха или работы\nКомпенсируем такси, каршеринг и трансферы — до 15 поездок в год\nУ меня нет карты лояльности ЦУМа или ДЛТ | Карта лояльности ЦУМа Orange в подарок Повышенный кэшбэк 8% бонусами по карте Orange |\nУ меня есть карта лояльности ЦУМа или ДЛТ White | Повысим статус карты лояльности ЦУМа до Orange бесплатно Повышенный кэшбэк 8% бонусами по карте Orange |\nУ меня есть карта лояльности ЦУМа или ДЛТ Orange | Повышенный кэшбэк 8% бонусами по карте Orange 1 год бесплатного обслуживания Alfa Only |\nУ меня есть карта лояльности ЦУМа или ДЛТ Black | Повышенный кэшбэк 20% бонусами по карте Black 1 год бесплатного обслуживания Alfa Only |\nОформите и получите карту Alfa Only\nИли зайдите в приложение Альфа‑Банка\nНа главном экране приложения или Альфа‑Онлайн и присоединитесь к программе\nСовершайте покупки и получайте повышенные бонусы в ЦУМе и ДЛТ
Name: text, dtype: object

[1860. 1856.  579. 1317.  468.  578.]
1859    Смс стали приходить!
Name: query, dtype: object
1855    alfas_01.11.2021_fin.pdf
Name: title, dtype: object
1855    \n\n\n\n📌\n\n📌\n\n📌\n\n📌\n\n📌\n\n📌\n\n📌\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n•\n\n
Name: text, dtype: object

[6588.  693.   15.  386.  114. 1731.]
6587    Вы можете прочитать сообщения выше?
Name: query, dtype: object
692    Как после тестирования перейти на продуктивную среду и принимать оплаты от реальных покупателей
Name: title, dtype: object
692    Куда обращаться, если возникли проблемы с переходом на продуктивную среду? Координаты служб сопровождения банка\nВопросы фрод-мониторинга (служба мониторинга мошенничества)\nEmail: fraudmonitoring@alfabank.ru\nВремя работы: круглосуточно\nВопросы технического характера\nEmail: acquiring@alfabank.ru\nВопросы, связанные с сопровождением договора (акты, реестры, возмещения), и другие\nEmail: acquiring@alfabank.ru\nТелефон: +7 495 974 83 79\nВремя работы: с 9:00 до 18:00 по Москве\nШаг 1. Поменяйте в личном кабинете первоначальные пароли для логинов из письма с продуктивными настройками.\nШаг 2. Включите фиксализацию в продуктивной среде, если арендуете онлайн-кассу у наших партнёров.\nШаг 3. Настройте оплату одним из способов подключения.\nШаг 4. Активируйте приём оплаты.\nЗайдите в продуктивный личный кабинет. Для этого введите логин с окончанием -api и первичный пароль — они содержатся в письме с инструкцией для подключения к продуктивной среде.\nСмените пароль для логина -api. Каким должен быть новый пароль:\nСодержит не менее 12 символов\nСодержит латинские символы в нижнем и верхнем регистре, цифры, символы из группы: ! " № ; : ? * ( ) + = /\ < > , . {}\nВы сменили пароль для логина -api. Теперь выйдите из личного кабинета и заново откройте страницу авторизации. Введите логин с окончанием -operator и первичный пароль из письма на почте.\nПридумайте новый пароль для логина -operator. Он также должен соответствовать требованиям по количеству и типу символов.\nДля входа в личный кабинет используйте логин -operator и ваш новый пароль к нему.\nЛогин -api не имеет доступа к личному кабинету. Он нужен при следующих способах подключения: с помощью модуля CMS или интеграции по api.\nОбратите внимание: вход в личный кабинет с логином -api возможен только один раз для создания нового пароля.\nЧтобы включить фискализацию в продуктивной среде:\nПодключите онлайн-кассу, зарегистрированную у одного из наших партнёров.\nЗаполните раздел «Настройки ОФД» в продуктивном личном кабинете.\nНастройка простых способов подключения без IT-специалиста\nВыставление ссылки на оплату\nЧтобы выставить ссылку на оплату реальному покупателю, зайдите в продуктивный личный кабинет и проделайте те же действия, что и во время тестирования.\nСоциальная сеть\nЧтобы создать ссылку на оплату, перейдите в продуктивный личный кабинет и используйте способ: выставление счёта на оплату в разделе «Счёт на оплату»\nКонструктор сайтов One Бизнес\nЗайдите в «Настройки сайта» в разделе «Интеграции» и снимите галочку с тестового режима. Также укажите продуктивный логин -api и новый пароль к нему, который задали ранее.\nЗатем перейдите в конструктор сайтов One Бизнес, нажмите «Создайте сайт бесплатно» и следуйте подсказкам.\nНастройка способов подключения с привлечением IT-специалиста\nПодключение с помощью платёжного виджета\nЗайдите в продуктивный личный кабинет в раздел «Настройки» → «Платёжный токен» и сгенерируйте токен.\nСкопируйте значение токена и укажите его в параметре data-token в скрипте на сайте.\nИзмените параметр скрипта с src="https://testpay.alfabank.ru/assets/alfa-payment.js" на src="https://pay2.alfabank.ru/assets/alfa-payment.js"\nИзмените значение параметра data-gateway с "test" на "pay"\nПодключение с помощью готового модуля для CMS и CRM\nЧтобы переключить платёжный модуль на продуктивную среду:\nОтключите тестовый режим в настройках модуля.\nИзмените адрес платёжного шлюза с тестового на продуктивный (если такое поле есть в настройках плагина).\nУкажите логин -api и пароль для продуктивной среды.\nПодключение по API\nРеализация взаимодействия через REST\nЧтобы переключить ресурс на продуктивную среду, смените адрес обращения к платёжному шлюзу https://pay.alfabank.ru/payment/rest/\nURL для доступа к методам REST:\nНазвание метода\nURL\nРегистрация заказа с предавторизацией\nРегистрация заказа\nРасширенный запрос состояния заказа\nЗапрос статистики по платежам за период\nЗапрос списка связок определённой банковской карты\nЗапрос списка связок клиента\nЗапрос состояния заказа\nЗапрос проверки вовлечённости карты в 3DS\nЗапрос проведения платежа по связке\nЗапрос отмены оплаты заказа\nЗапрос оплаты через внешнюю платёжную систему\nЗапрос на регулярный платёж\nЗапрос завершения оплаты заказа\nЗапрос добавления дополнительных параметров к заказу\nЗапрос деактивации связки\nЗапрос возврата средств оплаты заказа\nЗапрос активации связки\nЗапрос получения QR-кода по СБП\nЗапрос получения статуса платежа по QR коду по СБП\nДля этого проведите платёж в продуктивной среде:\nОформите заказ тем способов, который вы настроили.\nОплатите заказ реальной картой.\nПроверьте успешность в личном кабинете.\nПроверьте получение чека, если у вас настроена фискализация.
Name: text, dtype: object

[1570.  837.  481. 1705. 1721.   nan]
1569    заказать справку о реквизиты счета
Name: query, dtype: object
836    Документы для операций с векселями — «Альфа-Банк»
Name: title, dtype: object
836    Документы для операций с векселями\nДокументы для выдачи векселей\nДокументы для погашения векселей в срок\nДокументы для досрочного погашения векселей\nДокументы для мены векселей\nФорма доверенности\nОбразцы заполненных заявлений\nБланки векселей\nКонтактная информация\nПо вопросам выпуска и досрочного учета\nтел.: +7 495 795-36-60;\nтел.: +7 495 974-25-15 (доб. 8204)\nalfaveksel@alfabank.ru\nПо вопросам погашения\nв срок\nтел.: +7 495 788-64-08\nveksel@alfabank.ru
Name: text, dtype: object

[3853. 1789.  693. 1705.  444.   nan]
3852    До какого числа хранение моего стикера в г. Находка?
Name: query, dtype: object
1788    invest_prof_v5.pdf
Name: title, dtype: object

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

1065    Потеря дебетовой банковской карты — неприятность, хотя и не настолько разорительная, как может быть в случае с наличными. Пластик легко утратить из-за небольшого размера, а последствия зависят от того, где это произошло и насколько быстро будет действовать владелец. Рассказываем, как найти банковскую карту, если потеряли, что делать для сохранения денег на счёте.\nПри утрате платёжного средства владелец как минимум не сможет оплатить товар, который уже выбрал в магазине. Последствия могут быть серьёзнее, если пластик попадёт в руки нечестного человека. Скорее всего, вор не сумеет снять наличные с дебетовой карточки, так как для этого банкомат запрашивает пин-код. Но некоторые клиенты хранят эти четыре цифры вместе с пластиком. В таком случае мошеннику ничто не помешает обналичить всю сумму сразу и забрать, например, только что полученные пенсионные и другие социальные выплаты.\nЕсли же вы потеряли банковскую карту, злоумышленник с его помощью сможет делать покупки в обычных магазинах. При небольшой сумме касса не запрашивает пин-код, деньги просто списываются со счёта при прикладывании пластика. Так мошенник небольшими частями может потратить всё, что есть на балансе.\nСуществуют также интернет-магазины, в которых можно покупать без отправки присланного на привязанный номер телефона разового пароля. Имея в руках платёжное средство с уникальными данными, именем владельца и кодом CVV или CVV, мошенник легко потратит чужие деньги онлайн.\nЕдинственный плюс ситуации в том, что на дебетовой карточке, в отличие от кредитной, лежат лишь собственные сбережения клиента. Злоумышленник не сможет потратить ещё и деньги банка, тем самым устроив настоящему владельцу пластика дополнительные трудности.\nЕсли пластик не находится, владельцу надо делать следующее:\nпосмотреть в истории операций в мобильном приложении или в личном кабинете на сайте, совершалось ли списание после потери;\nперевести деньги на другой банковский счёт, если он есть, или снять их;\nзаблокировать карту.\nВсе опции доступны в мобильном приложении и Альфа‑Онлайн. Заранее полезно подключить смс-оповещения, с которыми клиент узнает об операциях по дебетовке сразу после совершения. Если это не он выполнял оплату или перевод, очевидно, что платёжное средство потеряно и необходимо защищать свои деньги.\nЧтобы узнать о списаниях со счёта, авторизуются в банковском приложении или Альфа-Онлайн. Там находят рубрику «История операций», в которой сохраняется информация о том, когда, куда и как отправились деньги, какой была сумма. Легко отследить, где последний раз пластиком пользовался владелец. Не исключено, что там же дебетовую карточку и потеряли, а значит, позже есть шанс обнаружить того, кто её забрал. Если этот человек начнёт покупать, каждое списание отразится в истории.\nСнять накопления с потерянной дебетовки владелец может несколькими способами:\nОтправить на другую карточку или банковский счёт. Это делают в приложении для смартфонов или Альфа-Онлайн в разделе переводов. Операция будет бесплатной, даже если отправить деньги на счёт другого клиента банка — родственника, супруга или друга.\nОбналичить с помощью смартфона. Для этого находят банкомат с функцией снятия денег без пластикового носителя. Чтобы выполнить операцию, по запросу устройства вводят номер телефона и присланный на него одноразовый пароль. Снятие в банкоматах Альфа-Банка и партнёров бесплатное.\nОбратиться в банковское отделение. Нужно оставить заявление на снятие наличных и показать паспорт. Этот способ подойдёт, если офис окажется совсем рядом, иначе операция будет выполнена нескоро.\nМожно ли снять наличные, если карта заблокирована? Снять деньги традиционным способом с заблокированной дебетовой карточки не получится. Это преимущество для владельца, ведь вор не украдёт с неё деньги даже с пин-кодом. Самому клиенту удастся их обналичить в офисе банка, написав заявление и предоставив паспорт.\nВладелец может на короткое время разблокировать потерянную дебетовку, выполнить перевод на другой счёт, снять наличные уже с него. Это важно делать быстро, заранее подготовив реквизиты или номер для осуществления операции. Иначе тот, кто нашёл дебетовку, успеет ею воспользоваться.\nЕщё есть вариант перевыпустить платёжное средство, которое потеряли, активировать новое до получения пластика и по QR-коду на смартфоне обналичить накопления в банкомате.\nЗаблокировать дебетовку нужно быстро любым из доступных способов:\nВ мобильном приложении на Android или в Альфа‑Онлайн на iPhone. В списке банковских продуктов находят утраченное платёжное средство и нажимают кнопку «Блокировать».\nЗвонком по телефону горячей линии банка. Опция бесплатная, а номер лучше заранее внести в список контактов на смартфоне, чтобы не пришлось искать в приложении.\nВ отделении банка. Это делается дольше, так как надо составить заявление и подтвердить личность документами, возможно, ещё и постоять в очереди.\nДеньги на счёте заблокированной карточки сохранятся.\nПодать заявку на перевыпуск нового платёжного средства можно в приложении, Альфа-Онлайн или в банке. Первые два варианта удобнее, но на изготовление пластика всё равно понадобится время. За досрочный перевыпуск платят 290 ₽.\nУ новой дебетовки будет тот же счёт, но изменится её номер, а также код CVV или CVC. Таким образом, деньги будут в сохранности, доступны клиенту, а его личные данные останутся закрытыми для посторонних. Если на карточку приходят пенсионные выплаты, не придётся сообщать о перевыпуске в Социальный фонд РФ.\nПользоваться дебетовой карточкой можно сразу после оформления, то есть обналичивать деньги, переводить, делать покупки, зарабатывать кэшбэк. Это реально благодаря её цифровой версии. Начисленный кэшбэк клиент получит на особый счёт, когда заберёт пластик.\nДействия клиента зависят от того, где потеряли пластик и кто его обнаружил. Если дебетовка всё время оставалась дома, не успела побывать в чужих руках, блокировалась в мобильном приложении или Альфа-Онлайн, её можно разблокировать там же и использовать дальше. Заказывать перевыпуск не надо.\nЕсли платёжное средство нашёл и вернул посторонний, правильнее не отменять блокировку и перевыпустить карточку. Даже при сохранении денег на счёте нельзя исключать хищение данных, которые потом могут использовать мошенники.\nЕсли потерянная дебетовка обнаружилась, а клиент уже получил перевыпущенную, старую карточку лучше уничтожить. Это позволит исключить путаницу в дальнейшем.\nПосле исчезновения денег с дебетовой карточки возможно их вернуть при выполнении следующих условий:\nВ течение суток сообщить в банк о несанкционированном списании через мобильное приложение, Альфа‑Онлайн или в отделении.\nРазъяснить, что не сообщали посторонним данные платёжного средства, не фотографировали дебетовку для всеобщего обозрения.\nЗапросить выписку баланса, чтобы получить распечатку по операциям.\nОспорить транзакции, выполненные посторонними людьми.\nЕсли все условия соблюдены, банк может вернуть деньги. Одновременно стоит подать заявление в полицию о потере карточки и её использовании неизвестными. Полицейские должны установить, кто тратил деньги без ведома владельца, так как это преступление.\nВ ситуации, когда вы потеряли дебетовку и смартфон, нужно обратиться к мобильному оператору за блокировкой телефонного номера. Тот, кто нашёл пластик и гаджет, лишится возможности использовать личные данные клиента и украсть всю сумму со счёта. Затем нужно обратиться в банковское отделение, чтобы сообщить об утрате платёжного средства и смартфона, получить рекомендации по дальнейшим действиям. С той же целью можно позвонить на горячую линию банка.\nПотерять дебетовую карточку неприятно, но не страшно, если быстро выполнить нужные для защиты денег и личных данных действия. Её просто восстановить, сохранив сбережения на счёте.\nЗаполните заявку, и Альфа-Карта ваша
Name: text, dtype: object

[ 782. 1677. 1042. 1853.  823. 1822.]
781    Добрый вечер! Мне муж перевел 0000 рублей для обязательного платежа, чтобы не выйти из беспроцентного периода. Скажите, пожалуйста, деньги упали туда, куда надо?
Name: query, dtype: object
1676    Услуга по накоплению «Копилка для зарплаты»💰
Name: title, dtype: object
1676    Любой процент отчисления\nМожно выбрать от 5% до 100% от каждой зарплаты.\nУдобное управление\nПодключить, отключить или изменить % можно в любой момент в приложении или позвонив специалисту банка.\nУслугу «Копилка для зарплаты» нельзя подключить к индивидуальной зарплатной карте, оформленной самостоятельно, не в рамках зарплатного проекта.\nВ рамках услуги «Копилка для зарплаты», подключенной до 20 июля 2020 года включительно, перечисления осуществляются на счёт «Накопилка». Для переключения услуги «Копилка для зарплаты» со счёта «Накопилка» на Альфа-Счёт, необходимо отключить услугу и подключить её заново.\nПри подключении услуги впервые — услуга автоматически подключается ко всем работодателям с одинаковыми параметрами;\nУслуга будет подключена автоматически при добавлении нового работодателя, от которого ранее вы не получали зарплату. Для него будут установлены параметры, соответствующие последней подключенной услуге, если сумма накопления была установлена как % от суммы заработной платы;\nПри изменении параметров хотя бы по одной услуге новый % будет применяться ко всем работодателям, включая компании, которые ранее не были подключены к услуге, либо по ним была установлена фиксированная сумма перевода.\nУслуга «Копилка для зарплаты» распространяется на все поступления на мой зарплатный счет?\nЯ не получаю заработную плату на карту Альфа‑Банка. Могу ли я подключить услугу «Копилка для зарплаты»?\nМогу ли я подключить услугу «Копилка для зарплаты», если я оформил индивидуальную зарплатную карту в Альфа-Банке?\nУ меня уже подключена услуга «Копилка для сдачи» с зачислением на счет «Накопилка». Могу ли я подключить услугу «Копилка для зарплаты»?\nКак быть, если в день поступления зарплаты, перевод средств на счет «Накопилка»/ «Альфа-Счёт» не был осуществлен?\nМожет ли указываемый процент от заработной платы быть не целым, а дробным?\nСкачайте PDF с подробными условиями\n173,7 Кб\n233,8 Кб\nУслуга «Копилка для зарплаты»
Name: text, dtype: object

[6216. 1677.  781.  118.   nan   nan]
6215    Здравствуйте! Я оплатила бизнес зал аэропорта через приложение Every Lounge, подскажите, в течение какого времени мне придет компенсация за него?
Name: query, dtype: object
1676    Услуга по накоплению «Копилка для зарплаты»💰
Name: title, dtype: object
1676    Любой процент отчисления\nМожно выбрать от 5% до 100% от каждой зарплаты.\nУдобное управление\nПодключить, отключить или изменить % можно в любой момент в приложении или позвонив специалисту банка.\nУслугу «Копилка для зарплаты» нельзя подключить к индивидуальной зарплатной карте, оформленной самостоятельно, не в рамках зарплатного проекта.\nВ рамках услуги «Копилка для зарплаты», подключенной до 20 июля 2020 года включительно, перечисления осуществляются на счёт «Накопилка». Для переключения услуги «Копилка для зарплаты» со счёта «Накопилка» на Альфа-Счёт, необходимо отключить услугу и подключить её заново.\nПри подключении услуги впервые — услуга автоматически подключается ко всем работодателям с одинаковыми параметрами;\nУслуга будет подключена автоматически при добавлении нового работодателя, от которого ранее вы не получали зарплату. Для него будут установлены параметры, соответствующие последней подключенной услуге, если сумма накопления была установлена как % от суммы заработной платы;\nПри изменении параметров хотя бы по одной услуге новый % будет применяться ко всем работодателям, включая компании, которые ранее не были подключены к услуге, либо по ним была установлена фиксированная сумма перевода.\nУслуга «Копилка для зарплаты» распространяется на все поступления на мой зарплатный счет?\nЯ не получаю заработную плату на карту Альфа‑Банка. Могу ли я подключить услугу «Копилка для зарплаты»?\nМогу ли я подключить услугу «Копилка для зарплаты», если я оформил индивидуальную зарплатную карту в Альфа-Банке?\nУ меня уже подключена услуга «Копилка для сдачи» с зачислением на счет «Накопилка». Могу ли я подключить услугу «Копилка для зарплаты»?\nКак быть, если в день поступления зарплаты, перевод средств на счет «Накопилка»/ «Альфа-Счёт» не был осуществлен?\nМожет ли указываемый процент от заработной платы быть не целым, а дробным?\nСкачайте PDF с подробными условиями\n173,7 Кб\n233,8 Кб\nУслуга «Копилка для зарплаты»
Name: text, dtype: object

[5875. 1620. 1537.  258. 1705.   nan]
5874    Прошу перевести средства со счёта на котором баланс 000 руб. на счёт кредитной карты
Name: query, dtype: object
1619    Чем дебетовая карта отличается от кредитной
Name: title, dtype: object
1619    Чем дебетовая карта отличается от кредитной\nНа дебетовой карте храним только ваши деньги. У кредитки же есть лимит — сумма, которую можете взять в долг у банка, если деньги закончились, а потом вернуть. С дебетовой картой так сделать не получится. Если у вас нет действующей кредитной карты, можем предложить до 100 000 рублей в рассрочку на повседневные траты, подробные условия можете найти в мобильном приложении.
Name: text, dtype: object

[3328.  579.  468.  578. 1705.   nan]
3327    Как установить alfa pay
Name: query, dtype: object
578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object
578    19.12.2024\nПодробнее: «Альфа‑Вклад»
Name: text, dtype: object

[ 664. 1910. 1746.  693. 1655.   nan]
663    Почему на закрытие счета код приходит на другой номер
Name: query, dtype: object
1909    Как заблокировать карту Альфа-банка?
Name: title, dtype: object
1909    Как заблокировать карту Альфа-банка?\nАльфа-банк даёт возможность оперативно заблокировать украденную или утерянную карту несколькими способами. В случае возникновения необходимости блокировки карты можно обратиться в ближайшее отделение.\n\nВ каких случаях необходима блокировка карты Альфа-Банка?\nСпособы блокировки карты Альфа-Банка\nС помощью СМС-сообщения\nКак разблокировать карту в Альфа Банке?\nАльфа-банк даёт возможность оперативно заблокировать украденную или утерянную карту несколькими способами. В случае возникновения необходимости блокировки карты можно обратиться в ближайшее отделение, заблокировать карту и подать заявку на её перевыпуск, но это совсем не обязательно. Достаточно иметь под рукой компьютер или телефон с доступом к интернету или даже без него. Полезно знать, как это делать, чтобы в случае необходимости быстро совершить блокировку и не дать шанса злоумышленникам.\n\nПри этом разблокировать карту можно не всегда тем же способом, которым вы её заблокировали. В некоторых случаях придётся всё же идти в офис банка для разблокировки.\n\nВ каких случаях необходима блокировка карты Альфа-Банка?\nПо большому счету, таких случаев – 2: если вы потеряли пластик или если его украли. Отличить первое от второго бывает непросто, поэтому сформулируем общее правило: если вы не знаете, где на данный момент находится ваша пластиковая карточка, то лучше ее заблокировать. Возможно, она находится за стиральной машиной, возможно – в руках вора. В первом случае вы отделаетесь легким испугом, во втором же ситуация будет куда хуже. И дело не только в том, что кто-то может воспользоваться вашими деньгами – чем позже вы отреагируете на пропажу, тем сложнее будет эти деньги вернуть через полицию.\n\nПоэтому блокировка карты при любых подозрениях на воровство – вполне разумный шаг, особенно – учитывая то, что пластик при необходимости можно оперативно разблокировать.\nСпособы блокировки карты Альфа-Банка\nПоскольку Альфа-Банк к блокировке карты относится серьезно, то и способов этой блокировки – предостаточно:\n\nинтернет-банкинг (Альфа-Клик, Альфа-Мобайл);\n\nотделение банка;\n\nСМСка;\n\nзвонок на горячую линию службы поддержки.\n\nЧерез интернет-банкинг «Альфа Клик»\nКак заблокировать любую карту Альфа-Банка через интернет:\n\nЗаходим в свой личный кабинет.\n\nВыбираем «Карты» -> «Блокировка».\n\nВыбираем карточку.\n\nГотово.\n\nСпособ безотказен, работает и днем, и ночью, пластик блокируется мгновенно. Из минусов – нужно помнить логин и пароль к личному кабинету, нужно иметь доступ к браузеру и интернету. Это бывает неудобным, особенно – когда вы потеряли карточку где-то в путешествии.\n\nКстати, помните, что заходить в свой личный кабинет с неизвестных устройств – небезопасно, потому что данные для входа могут своровать различными программами.\nВ отделении банка\nПожалуй, самый неудобный из всех возможных способов – нужно идти в отделение Альфа-Банка с паспортом. С другой стороны, если у вас нет доступа к интернету и телефону, этот способ – единственный доступный. Итак, как заблокировать кредитную или дебетовую карту Альфа-Банка в отделении:\n\nПриходим в отделение с паспортом.\n\nПоказываем сотруднику паспорт, объясняем ситуацию.\n\nЖдем, пока сотрудник найдет нас в базе по паспортным данным.\n\nГотово.\n\nС помощью СМС-сообщения\nСамый быстрый способ блокировки карты – через мобильный телефон. Альфа-Банк предлагает одновременно целых три варианта действий, чтобы заблокировать карту при помощи телефона: через Альфа-чек, Альфа-консультант и Альфа-мобайл. Так, это можно сделать, отправив SMS-сообщение «block» по короткому номеру 2265. В ответ клиент получит список карт с обозначением последних 4-х цифр каждой из них, на которое нужно ответить в формате «block *xxxx», где хххх – четыре последние цифры номера блокируемой карты. Функция блокировки есть в мобильном приложении Альфа-мобайл.\n\nЧерез мобильное приложение\nКак заблокировать карту Альфа-Банка через мобильное приложение:\n\nЗаходим в личный кабинет.\n\nОткрываем меню «Счета и карты».\n\nВыбираем нужную карточку.\n\nЛистаем вниз открывшийся список действии, ищем «Заблокировать».\n\nЖмем, подтверждаем действие. Пластик мгновенно блокируется, теперь оплатить что-то с него невозможно.\n\nЭтот метод – пожалуй, самый удобный. Телефон обычно под рукой, найти бесплатный Wi-Fi – не проблема, все делается в пару нажатий.\n\nПо телефону\nКак заблокировать карту Альфа-Банка по мобильному или домашнему телефону? Чтобы произвести блокировку через горячую линию, вам нужно позвонить по номеру 8 800 200-00-00. Оператор колл-центра попросит вас представиться и назвать свою дату рождения, найдет вас в базе и попросит назвать секретное слово. Называете – и говорите, что нужно заблокировать карточку. Если у вас их – несколько, оператор попросит уточнить, какую именно, после чего произведет блокировку. Этот способ – второй по скорости, если у вас нет доступа к интернету, лидирует же СМС-сообщение.\n\nКак разблокировать карту в Альфа Банке?\nИтак, оказалось, что кредитка не украдена – она спокойно дожидалась вас в другой сумочке. Теперь нужно произвести разблокировку, чтобы пользоваться деньгами. Как это сделать?\n\nПервый вариант – в отделении банка. Приходите с паспортом, говорите: «Нужно разблокировать». Через пару минут все будет готово.\n\nВторой вариант – через СМС. Клиент с номера, на который подключен мобильный банкинг, шлет на номер +7 903 767 22 65 СМС вида «unblock *1234», где 1234 – последние цифры номера карточки. Если не помните их – сначала отправьте СМС со словом «unblock», в ответе получите все привязанные карточки.\n\nТретий вариант – через мобильное приложение. Порядок действий – такой же, как и при блокировке, только вместо пункта меню «Заблокировать» будет пункт «Разблокировать», который и надо нажать.\n\nНаконец, последний вариант – звонок в техподдержку. Звоните, представляетесь, называете секретное слово, просите произвести разблокировку.
Name: text, dtype: object

[5839.  823. 1301. 1746. 1317. 1705.]
5838    Перевести собственные деньги
Name: query, dtype: object
822    Оборотный кредит для среднего и крупного бизнеса в 🅰️ Альфа‑Банке — Кредитование под оборотные средства юридических лиц
Name: title, dtype: object

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [35]:
print(data[data.web_id == 579]['title'])

578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object

In [14]:
questions

      q_id                                              query
0        1                                        Номер счета
1        2                              Где узнать бик и счёт
2        3  Мне не приходят коды для подтверждения данной ...
3        4  Оформила рассрочку ,но уведомлений никаких не ...
4        5  Здравствуйте, когда смогу пользоваться кредитн...
...    ...                                                ...
6972  6973  Здравствуйте, оплатил вчера ЖКХ а кэшбек не на...
6973  6974  Здравствуйте,  можно ли заказать реквизиты бан...
6974  6975  Здравствуйте, подскажите пожалуйста где я могу...
6975  6976                  Реквизиты для оплаты номера карты
6976  6977  Можно ли отключить автопополнение брокерского ...

[6977 rows x 2 columns]