In [1]:
import pandas as pd

# Data Loading

In [2]:
questions = pd.read_csv('../data/raw/questions_clean.csv')

In [3]:
data = pd.read_csv('../data/raw/websites_updated.csv')

# Mini sample for test

In [30]:
questions.sample(200).to_csv('../data/raw/questions_clean_sample_200.csv')

In [33]:
data.sample(200).to_csv('../data/raw/websites_updated_sample_200.csv')

# EDA

In [43]:
data.head(3)

,web_id,url,kind,title,text
0,1,https://alfabank.ru/,html,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,https://alfabank.ru/a-club/,html,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,https://alfabank.ru/a-club/ultimate/,html,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

In [44]:
questions.head()

   q_id                                                     query
0     1                                               Номер счета
1     2                                     Где узнать бик и счёт
2     3    Мне не приходят коды для подтверждения данной операции
3     4      Оформила рассрочку ,но уведомлений никаких не пришло
4     5  Здравствуйте, когда смогу пользоваться кредитной картой?

In [9]:
data.kind.value_counts()

kind
html        1802
document     135
Name: count, dtype: int64

In [ ]:
data[data.kind=='document'].head(3)

In [18]:
data.text.iloc[0]

'Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке'

# Extracting importance columns

In [47]:
data_clean = data[['web_id', 'title', 'text']]

In [49]:
data_clean.head(3)

,web_id,title,text
0,1,"Альфа-Банк - кредитные и дебетовые карты, кредиты наличными, автокредитование, ипотека и другие банковские услуги физическим и юридическим лицам – Альфа-Банк","Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке"
1,2,А-Клуб. Деньги имеют значение,"Брокерские услуги\nОткрытие брокерского счёта в приложении Альфа‑Инвестиции. Расширенный инструментарий: биржевая, внебиржевая и маржинальная торговля, биржевые структурные облигации, первичные размещения\nИнвестиционное консультирование\nДля инвесторов с брокерским счётом в Альфа‑Инвестициях — привлекательные условия и автоматизированная консультационная платформа\nАльтернативные инвестиции\nИнвестирование в фонды недвижимости, private equity и венчурные фонды, капитал быстрорастущих компаний\nСтраховые и пенсионные программы\nИнвестиционное и накопительное страхование жизни. Дополнительные юридические и налоговые преимущества. Структурирование передачи капитала\nАльфа‑Капитал\nИндивидуальные или готовые стратегии, открытые ПИФы и БПИФы — для простого и эффективного доступа на рынок, ЗПИФы — для структурирования капитала и реализации индивидуальных стратегий управления благосостоянием\nИндивидуальные решения\nСтруктурирование активов в РФ и за рубежом, создание сложных финансовых продуктов по запросу\nДепозиты и накопительные счета\nВозможность установления индивидуальных тарифов\nБанковские карты\nВозможность привязать карты к счетам в 23 валютах; карты с привилегиями и кэшбэком до 15%\nДрагоценные металлы и камни\nМерные и стандартные слитки золота, бриллианты инвестиционного качества\nСделки через аккредитив или депозитарий\nБезопасность и гарантия сделок любой сложности\nБиометрический депозитарий\nУсиленное круглосуточное хранилище\nКредитование\nИпотека по паспорту на срок до 30 лет на строящееся и готовое жильё, включая рефинансирование\nПлатёжные аксессуары\nКерамические платёжные кольца с бесконтакной оплатой\nПеревозка, доставка и инкассация наличных\nСвоя служба инкассации\nЛучший сервис Private Banking\nПо версии Frank RG\nЛучший российский банк для состоятельных клиентов\nПо версии Wealth Navigator\nЛучший Private Banking в 13 номинациях\nПо версии Euromoney\nЧастые вопросы\nКакая минимальная и максимальная сумма пополнения брокерского счёта для клиентов в возрасте от 14 до 18 лет?\nХотите получить больше информации?\nСвяжитесь с нами, и мы ответим на все вопросы\n+7 495 777 32 55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"
2,3,А-Клуб. Деньги имеют значение,"Хотите получить больше информации?\nПозвоните нам и мы ответим на все вопросы\n+7 495 777-32-55\na-club@alfabank.ru\n© 2001-2025. АО «Альфа-Банк», официальный сайт. Генеральная лицензия Банка России № 1326 от 16 января 2015 г. АО «Альфа-Банк» является участником системы обязательного страхования вкладов. Информация о процентных ставках по договорам банковского вклада с физическими лицами. Центр раскрытия корпоративной информации. Информация профессионального участника рынка ценных бумаг. Информация о лицах, под контролем либо значительным влиянием которых находится Банк. Ул. Каланчевская, 27, Москва, 107078. АО «Альфа-Банк» использует файлы «cookie» с целью персонализации сервисов и повышения удобства пользования веб-сайтом. Если вы не хотите, чтобы ваши пользовательские данные обрабатывались, пожалуйста, ограничьте их использование в своём браузере\nАО «Альфа-Банк» является оператором по обработке персональных данных, информация об обработке персональных данных и сведения о реализуемых требованиях к защите персональных данных отражены в Политике в отношении обработки персональных данных"

# Answer checking

In [6]:
pd.set_option('display.max_colwidth', None)

In [61]:
ans.values

array([[1136, 1, 1192, '1192_0',
        'Как войти в Альфа-Онлайн\nГде найти номер карты или счёта\nЧто делать, если я не помню логин и пароль\nКак создать иконку Альфа-Онлайн\nЕсли не получается войти в Альфа-Онлайн, позвоните в поддержку: 8 80',
        0.6250022053718567],
       [1136, 2, 1904, '1904_0',
        'Как активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.',
        0.5892703533172607],
       [1136, 3, 1523, '1523_0',
        'Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк',
        0.5331138968467712],
       ...,
       [2481, 3, 1607, '1607_0',
        'Лента операций\nКак устроен интернет-банк\nГде посмотреть все мои счета?\nЕсть 2 способа посмотреть все счета:\nНа главной странице интернет-банка в блоке Счета на главной нажмите на кнопку Все счета.\nВ л',
        0.5648996829986572],
       [2481, 4, 480, '480_0',
        'Архив тарифов на комплексное банковское обслуживание',
        0.5639533996582031],
       [2481, 5, 1903, '1903_0',
        'В каких банках смогу снять наличные?\nОплачивать покупки и снимать наличные сможете в этих:\n\n• В Армении — во всех банках-участниках платёжной системы ArCa.\n• В Таджикистане — во всех банках-участниках',
        0.5472157001495361]], shape=(1000, 6), dtype=object)

In [60]:
ans.head(10)

,q_id,rank,web_id,chunk_id,chunk_text,score
0,1136,1,1192,1192_0,"Как войти в Альфа-Онлайн\nГде найти номер карты или счёта\nЧто делать, если я не помню логин и пароль\nКак создать иконку Альфа-Онлайн\nЕсли не получается войти в Альфа-Онлайн, позвоните в поддержку: 8 80",0.625002
1,1136,2,1904,1904_0,Как активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.,0.589270
2,1136,3,1523,1523_0,"Общая информация Мобильное приложение и Альфа-Онлайн Комиссии по карте Перевыпуск, блокировка и закрытие Как перестать пользоваться картой? Как пользоваться картой? Начало использования Всё про кэшбэк",0.533114
3,1136,4,1589,1589_0,Как пользоваться картой\nКак перестать пользоваться картой?\nПомощь\nДебетовые карты\nКак активировать карту?\nВ мобильном приложении или Альфа-Онлайн: Все мои продукты → Счёт карты → Установите пин-код.\nК,0.524637
4,1136,5,44,44_0,"Выберите приложение, операционную систему и пользуйтесь",0.516911
5,2185,1,890,890_1,"и зарегистрировал её заново. Но в приложении не отображаются покупки, оплаченные через Mir Pay. Почему? Я расплатился пластиковой картой в магазине, но не вижу покупку в приложении Mir Pay. Почему? Ка",0.626835
6,2185,2,1921,1921_6,"браузере на символ замка, который появляется при посещении сайтов, разрешающих безопасную передачу данных. Он должен быть выдан первоначальному владельцу веб-сайта. Мошенники списали деньги с карты: ч",0.618829
7,2185,3,1358,1358_0,08.08.2013\nС 1 августа 2013 года Альфа-Банк изменил процентные ставки по кредитным картам.,0.598648
8,2185,4,1887,1887_0,"Тарифы и комиссии\nПереводы c карты на карту\nКэшбэк\nНачало использования\nОбщая информация по карте\nВыпуск карты\nЕсли карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически?\n",0.596366
9,2185,5,1249,1249_0,Подтвердите запрос пополнения вашего счёта из другого банка\nПродолжить в Альфа-Онлайн,0.593668

In [295]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [201]:
for j, i in enumerate(ans.values):
    if j <= 1000:
        print('------НАЧАЛО-------')
        print('Question:')
        print(f'" { questions[questions.q_id == i[0]]['query']} "')
        print('Title of doc:')
        print(f'"{data[data.web_id == i[2]]['title']}"')
        print('Chunk from doc:')
        print(f'"{i[4]}"')
        #print(data[data.web_idк == i[1]]['text'])
        print(f'score : {i[5]}')
        print('-------КОНЕЦ--------')
        print()

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1566    Мобильный банк Альфа-Онлайн
Name: title, dtype: object"
Chunk from doc:
"Ещё нужен номер карты Номер карты Номер карты Продолжить"
score : 0.6654100474654389
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"15    Без названия
Name: title, dtype: object"
Chunk from doc:
"Введите номер телефона Телефон Телефон Продолжить"
score : 0.6040790212237358
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"402    Проценты на остаток брокерского счёта
Name: title, dtype: object"
Chunk from doc:
"Проценты на остаток брокерского счёта"
score : 0.578015148639679
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"671    Открыть расчётный счёт для бизнеса – Альфа-Банк 🅰️ Бесплатное открытие РС онлайн. Тарифы и стоимость обслуживания счета
Name: title, dtype: object"
Chunk from doc:
"Сколько счетов можно открывать в рамках тарифа? Вы можете открыть только один счёт в рублях. Валютных счетов в рамках этого тарифа нет. Когда списывается комиссия за обслуживание? Обслуживание счёта 0"
score : 0.5666688084602356
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1248    Без названия
Name: title, dtype: object"
Chunk from doc:
"Подтвердите запрос пополнения вашего счёта из другого банка Продолжить в Альфа-Онлайн"
score : 0.5664403438568115
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"1566    Мобильный банк Альфа-Онлайн
Name: title, dtype: object"
Chunk from doc:
"Ещё нужен номер карты Номер карты Номер карты Продолжить"
score : 0.5148413181304932
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"1612    Как получить справку или выписку по дебетовой карте?
Name: title, dtype: object"
Chunk from doc:
"Как получить справку или выписку по дебетовой карте? Получить справку можно в мобильном приложении или Альфа-Онлайн: Счёт карты → Справки и выписки. Справку в формате PDF с подписью и синей печатью от"
score : 0.4916815647027875
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"1606    Где посмотреть все мои счета?
Name: title, dtype: object"
Chunk from doc:
"Лента операций Как устроен интернет-банк Где посмотреть все мои счета? Есть 2 способа посмотреть все счета: На главной странице интернет-банка в блоке Счета на главной нажмите на кнопку Все счета. В л"
score : 0.4916204757360527
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"671    Открыть расчётный счёт для бизнеса – Альфа-Банк 🅰️ Бесплатное открытие РС онлайн. Тарифы и стоимость обслуживания счета
Name: title, dtype: object"
Chunk from doc:
"Сколько счетов можно открывать в рамках тарифа? Вы можете открыть только один счёт в рублях. Валютных счетов в рамках этого тарифа нет. Когда списывается комиссия за обслуживание? Обслуживание счёта 0"
score : 0.4898522513462979
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"97    Дебетовая карта с кэшбэком в аптеках: оформите онлайн в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"а затем введите сумму и подтвердите перевод. Мы комиссию за такой перевод не возьмём, но может взять банк, с которого переводите деньги. Как настроить пуш или смс-уведомления? Откройте приложение и в "
score : 0.4826572251846776
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"109    Подтвердите учётную запись на портале «Госуслуги»
Name: title, dtype: object"
Chunk from doc:
"Что нужно для подтверждения учётной записи? Как создать или подтвердить учётную запись Шаг 1 Шаг 2 Шаг 3 Шаг 4"
score : 0.5859506950109404
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1704    dogovor_cbo_1072025.pdf
Name: title, dtype: object"
Chunk from doc:
"или операций и действий, для совершения которых не используется Секретный код. Одноразовый пароль применяется при проведении операций и действий посредством Интернет Банка «Альфа-Клик» с использование"
score : 0.5664022650016984
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1703    dogovor_cbo_1082025.pdf
Name: title, dtype: object"
Chunk from doc:
"или операций и действий, для совершения которых не используется Секретный код. Одноразовый пароль применяется при проведении операций и действий посредством Интернет Банка «Альфа-Клик» с использование"
score : 0.5664022650016984
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1248    Без названия
Name: title, dtype: object"
Chunk from doc:
"Подтвердите запрос пополнения вашего счёта из другого банка Продолжить в Альфа-Онлайн"
score : 0.5617532730102539
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"115    Ваши деньги в безопасности
Name: title, dtype: object"
Chunk from doc:
"одноразовых кодов в смс или пушах, как раньше? Я хочу, чтобы текущий пароль не менялся Почему при подтверждении операции у меня не запросили секретный код? Почему для подтверждения некоторых операций "
score : 0.5617265354641522
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1631    Семейная ипотека в 🅰️ Альфа-Банке — Оформить ипотеку с господдержкой для семей с детьми под низкий процент
Name: title, dtype: object"
Chunk from doc:
"стоимость кредита — это сумма всех обязательных расходов без учета досрочного погашения Типы недвижимости, доступные для ипотеки Квартира Требования к недвижимости Квартира должна находиться в доме, к"
score : 0.5896973230631835
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"222    Что такое рефинансирование ипотеки? | Статьи про ипотеку от 🅰️ Альфа‑Банка
Name: title, dtype: object"
Chunk from doc:
"было несколько рефинансирований; отчёт об оценке (для вторичного жилья) — кстати, в Альфа‑Банке есть возможность воспользоваться опцией оформления отчёта об оценке с самоосмотром. Опцией можно восполь"
score : 0.5892035961151123
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"281    Статьи для крупного бизнеса и корпоративных клиентов 🅰️ Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"РКО Кредиты ВЭД Факторинг Зарплатный проект РКО Кредиты ВЭД Факторинг Зарплатный проект Всё для крупного бизнеса и корпоративных клиентов"
score : 0.5815459489822388
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1012    Ипотека в Ростове-на-Дону — Оформить ипотеку в Альфа-Банке 🅰️ — Онлайн получение одобрения на ипотечный кредит
Name: title, dtype: object"
Chunk from doc:
"До 100 млн ₽ сумма кредита До 30 лет срок кредита От 30,1% первоначальный взнос Другие предложения по ипотеке По цели По сроку Условия По сумме По городам Ипотека в Ростове-на-Дону Дополнительная инфо"
score : 0.578197717666626
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"247    Ипотека с первоначальным взносом от 🅰️ Альфа⁠-⁠Банка — Взять ипотечный кредит с минимальным первоначальным взносом
Name: title, dtype: object"
Chunk from doc:
"РФ СНИЛС Справки о доходах (предоставляется после одобрения вместе с документами по сделке) Другие предложения по ипотеке По цели По сроку Условия С использованием материнского капитала С первоначальн"
score : 0.5771434903144836
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"164    Кредитные карты с большим льготным периодом без процентов - оформить кредитку с выгодными условиями в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"У вас есть контактный телефон: мобильный или домашний Мне срочно нужны деньги. Я могу рассчитывать на них сегодня? Да. Если заявка отправлена до 14:00, карточку, на которую уже зачислена одобренная су"
score : 0.5310963568119761
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"1638    Приложение банка для самозанятых от 🅰️ Альфа‑Банка — Удобное мобильное приложение для самозанятых
Name: title, dtype: object"
Chunk from doc:
"дома Переведём самозанятость к нам Пара кликов — и вы самозанятый с Альфа‑Банком Оформите самозанятость в Альфа‑Банке Другие предложения для самозанятых Полезные инструменты Приложение Сфера деятельно"
score : 0.5255358976406679
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"469    Кредитная карта для Бизнеса от Альфа-Банка - оплачивайте расходы новой кредитной для ИП
Name: title, dtype: object"
Chunk from doc:
"а бухгалтер оформляет по ним авансовый отчёт. При системах налогообложения ИП на патенте, УСН «Доходы» — расходы по бизнес-карте можно не учитывать. Что такое МСС-код? MCC-код — это четырёхзначный код"
score : 0.5202192328087112
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"619    Кредитная карта для Бизнеса от Альфа-Банка - оплачивайте расходы новой кредитной для ИП
Name: title, dtype: object"
Chunk from doc:
"а бухгалтер оформляет по ним авансовый отчёт. При системах налогообложения ИП на патенте, УСН «Доходы» — расходы по бизнес-карте можно не учитывать. Что такое МСС-код? MCC-код — это четырёхзначный код"
score : 0.5202192328087112
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"443    Как получить статус Квалифицированный инвестор в Альфа-Инвестиции
Name: title, dtype: object"
Chunk from doc:
"ценными бумагами Трейдер Если ваш оборот превышает 82 000 ₽ в месяц От 82 000 ₽ Оптимальная сумма оборота в месяц 199 ₽ в месяц Обслуживание От 0,014% Комиссия за операции с ценными бумагами При откры"
score : 0.514022707939148
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"1886    Если карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически?
Name: title, dtype: object"
Chunk from doc:
"Тарифы и комиссии Переводы c карты на карту Кэшбэк Начало использования Общая информация по карте Выпуск карты Если карта Альфа-Бизнес с кэшбэком была перевыпущена, кэшбэк подключается автоматически? "
score : 0.5984649961003331
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"865    Бесконтактные пластиковые карты — заказать бесконтактную nfc карту в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"Дебетовая карта Альфа-Банка и билайн Бесплатно выпуск и обслуживание 25% кэшбэк за оплату связи и услуг билайн Без комиссии все переводы и платежи Сегодня даже школьнику известно, как пользоваться бес"
score : 0.5926528573036194
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"1870    timemoney_pu_01112020.pdf
Name: title, dtype: object"
Chunk from doc:
"НАКОПИТЕЛЬНЫЙ СЧЕТ «ЦЕННОЕ ВРЕМЯ» С 01.10.2018 года открытие счета прекращено редакция от 01.11.2020г.  Пополнять счет можно:    в Интернет-банке «Альфа-Клик» и Мобильном банке «Альфа – Мобайл» в "
score : 0.5902292728424072
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"1829    timemoney_pu_1042024.pdf
Name: title, dtype: object"
Chunk from doc:
"НАКОПИТЕЛЬНЫЙ СЧЕТ «ЦЕННОЕ ВРЕМЯ» С 01.10.2018 года открытие счета прекращено  Пополнять счет можно: редакция от 01.04.2024    в Интернет-банке «Альфа-Клик» и Мобильном банке «Альфа – Мобайл» в ба"
score : 0.5901954174041748
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"1833    timemoney_pu_01012021.pdf
Name: title, dtype: object"
Chunk from doc:
"НАКОПИТЕЛЬНЫЙ СЧЕТ «ЦЕННОЕ ВРЕМЯ» С 01.10.2018 года открытие счета прекращено редакция от 01.01.2021г.  Пополнять счет можно:    в Интернет-банке «Альфа-Клик» и Мобильном банке «Альфа – Мобайл» в "
score : 0.5885851383209229
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1905    Как закрыть счёт, к которому была привязана карта?
Name: title, dtype: object"
Chunk from doc:
"Как закрыть счёт, к которому была привязана карта? Выберите его на главном экране приложения или Альфа-Онлайн: Действия → Закрыть счёт. Остаток на счёте можете перевести на другой счёт, отправить на м"
score : 0.6333527082823986
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"88    Карта Альфа‑Cash для среднего и крупного бизнеса — 🅰️ Альфа-Банк
Name: title, dtype: object"
Chunk from doc:
"сети интернет? Да, в торгово-сервисных предприятиях и сети интернет вы можете оплачивать: товары и услуги для поддержания основной деятельности компании; представительские, хозяйственные и накладные р"
score : 0.6235480438994928
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"164    Кредитные карты с большим льготным периодом без процентов - оформить кредитку с выгодными условиями в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"На эту покупку мы не будем начислять проценты 60 дней Когда вы вы погасите долг за телефон, 60 дней без процентов возобновятся Кредитка подходит и для крупных, и для регулярных покупок. На них распрос"
score : 0.6144342146059104
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1603    Я могу выбрать логин для входа в Альфа-Кредит?
Name: title, dtype: object"
Chunk from doc:
"Общие сведения Я могу выбрать логин для входа в Альфа-Кредит? Самостоятельно выбрать логин нельзя. При подключении к Альфа-Кредиту мы отправили ваш логин на электронную почту, а временный пароль — в с"
score : 0.6072360884430114
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1195    Кэшбэк на золото
Name: title, dtype: object"
Chunk from doc:
"Инвестиции → виджет Курсы валют и металлов Нажмите на любой из металлов, чтобы появилось предложение открыть счёт. В Альфа‑Онлайн Зайдите в раздел Витрина металлов → нажмите Открыть счёт → выберите Сч"
score : 0.6062069751348284
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"402    Проценты на остаток брокерского счёта
Name: title, dtype: object"
Chunk from doc:
"Проценты на остаток брокерского счёта"
score : 0.6100801825523376
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"479    Архив тарифов на комплексное банковское обслуживание
Name: title, dtype: object"
Chunk from doc:
"Архив тарифов на комплексное банковское обслуживание"
score : 0.6094796061515808
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"861    Телефонный центр «Альфа-Консультант» — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"справочную информацию (курсы валют, адреса дополнительных офисов, режим работы и т. д.) Оформить претензию и уточнить статус ее рассмотрения Получить подробную консультацию по новым и действующим прод"
score : 0.5620109438896179
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"1722    Управление ликвидностью бизнеса в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"Платёжный календарь Бюджетирование и контроль Управление ликвидностью"
score : 0.5501988530158997
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"110    Удаленные каналы обслуживания Альфа-Банка — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Удаленные каналы обслуживания Альфа-Банка"
score : 0.5497668385505676
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"164    Кредитные карты с большим льготным периодом без процентов - оформить кредитку с выгодными условиями в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"услуги Альфа‑Чек: откройте в приложении Настройки → Операции по картам, выберите нужную карту и подключите уведомления Какова стоимость обслуживания кредитной карты с грейсом на снятие? Первый год обс"
score : 0.6066736783334309
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"97    Дебетовая карта с кэшбэком в аптеках: оформите онлайн в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"а затем введите сумму и подтвердите перевод. Мы комиссию за такой перевод не возьмём, но может взять банк, с которого переводите деньги. Как настроить пуш или смс-уведомления? Откройте приложение и в "
score : 0.5980946373742037
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"1607    Где посмотреть тарифы по бизнес-карте?
Name: title, dtype: object"
Chunk from doc:
"Использование бизнес-карты Использование кредитной бизнес-карты Выпуск бизнес-карты Где посмотреть тарифы по бизнес-карте? Перейдите в раздел Мои сервисы → Карты. Нажмите на кнопку Тарифы. Откроется с"
score : 0.5921484040046767
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"1606    Где посмотреть все мои счета?
Name: title, dtype: object"
Chunk from doc:
"Лента операций Как устроен интернет-банк Где посмотреть все мои счета? Есть 2 способа посмотреть все счета: На главной странице интернет-банка в блоке Счета на главной нажмите на кнопку Все счета. В л"
score : 0.580306067190181
-------КОНЕЦ--------


In [35]:
print(data[data.web_id == 579]['title'])

578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object

In [14]:
questions

      q_id                                              query
0        1                                        Номер счета
1        2                              Где узнать бик и счёт
2        3  Мне не приходят коды для подтверждения данной ...
3        4  Оформила рассрочку ,но уведомлений никаких не ...
4        5  Здравствуйте, когда смогу пользоваться кредитн...
...    ...                                                ...
6972  6973  Здравствуйте, оплатил вчера ЖКХ а кэшбек не на...
6973  6974  Здравствуйте,  можно ли заказать реквизиты бан...
6974  6975  Здравствуйте, подскажите пожалуйста где я могу...
6975  6976                  Реквизиты для оплаты номера карты
6976  6977  Можно ли отключить автопополнение брокерского ...

[6977 rows x 2 columns]

# Comparing with benchmark

In [108]:
bench = pd.read_csv('../data/processed/top5.csv', index_col=5)

In [109]:
bench = bench.drop(['0', '1', '2', '3', '4'], axis=1)

In [111]:
bench.head()

                                 lst
q_id
1       [1567, 1607, 496, 114, 1808]
2        [368, 599, 597, 1263, 1906]
3      [1175, 386, 1516, 1165, 1166]
4       [1043, 1620, 659, 1461, 478]
5     [1520, 1621, 1556, 1538, 1564]

In [115]:
bench.loc[5]

lst    [1520, 1621, 1556, 1538, 1564]
Name: 5, dtype: object

In [119]:
data[data.web_id==1564]

,web_id,url,kind,title,text
1563,1564,https://alfabank.ru/help/t/corp/debitcards/debetovaya-karta-aeroflot/,html,"Дебетовая карта Аэрофлот: все, что нужно знать","Общая информация\nМобильное приложение и Альфа-Онлайн\nКомиссии по карте\nПеревыпуск, блокировка и закрытие\nКак перестать пользоваться картой?\nКак пользоваться картой?\nНачало использования\nВсё про кэшбэк рублями\nСправки и выписки\nПрограмма “Деньги вам и друзьям”\nВсё про кэшбэк милями и баллами\nВсё о комиссиях и лимитах\nКэшбэк от партнёров\nИзготовление и доставка\nПлатежи и переводы"

In [144]:
list(map(int, bench.iloc[1].lst.replace(' ', '').replace('[', '').replace(']', '').split(',')))

[368, 599, 597, 1263, 1906]

In [ ]:
e

In [147]:
bench

                                 lst
q_id
1       [1567, 1607, 496, 114, 1808]
2        [368, 599, 597, 1263, 1906]
3      [1175, 386, 1516, 1165, 1166]
4       [1043, 1620, 659, 1461, 478]
5     [1520, 1621, 1556, 1538, 1564]
...                              ...
96       [1894, 123, 852, 886, 1749]
97       [1863, 1290, 90, 398, 1861]
98       [1916, 368, 1072, 326, 219]
99        [745, 704, 1734, 846, 706]
100     [1567, 114, 321, 1615, 1071]

[100 rows x 1 columns]

In [158]:
bench.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100],
      dtype='int64', name='q_id')

In [293]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [294]:
score = 0
for i in ans.values:
    if i[0] in bench.index:
        #print(i[0])
        #print(i[2])
        bench_line = list(map(int, bench.loc[i[0]].lst.replace(' ', '').replace('[', '').replace(']', '').split(',')))
        if i[2] in bench_line : score += 1
        #print(bench_line)
print(score / 100)

0.45

In [297]:
ans = ans[['q_id', 'chunk_id']]

In [ ]:
import pandas as pd
import ast

# === Загружаем CSV ===
ground_truth = pd.read_csv("truth.csv")           # размеченные web_id
predictions = pd.read_csv("predictions_rag.csv")  # предсказания RAG

def parse_web_list(s):
    """Парсим строку вида '[1, 2, 3]' в список чисел"""
    return ast.literal_eval(s) if isinstance(s, str) else []

ground_truth["web_list"] = ground_truth["web_list"].apply(parse_web_list)
predictions["web_list"] = predictions["web_list"].apply(parse_web_list)

#  Подсчёт Hit@K
K = 5
hits = []

for _, row in ground_truth.iterrows():
    qid = row["q_id"]
    true_ids = set(row["web_list"])

    # Проверяем, есть ли этот q_id в предсказаниях
    pred_row = predictions[predictions["q_id"] == qid]
    if pred_row.empty:
        continue

    pred_ids = set(pred_row.iloc[0]["web_list"][:K])

    # Hit@K = 1, если есть хотя бы одно совпадение
    hit = 1 if len(true_ids & pred_ids) > 0 else 0
    hits.append(hit)

# Средний результат
hit_at_k = sum(hits) / len(hits) if hits else 0
print(f"Hit@{K}: {hit_at_k:.4f}")

# по каждому запросу
for idx, h in enumerate(hits):
    print(f"q_id={ground_truth.iloc[idx]['q_id']}: hit={h}")

# Загрузка решения

In [265]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [255]:
sample = pd.read_csv('../data/raw/sample_submission.csv')

In [256]:
str([1, 23])

'[1, 23]'

In [257]:
sample

      q_id                        web_list
0        1     [935, 687, 963, 1893, 1885]
1        2    [1660, 1882, 1040, 1090, 64]
2        3      [1246, 698, 465, 757, 307]
3        4      [366, 1625, 461, 279, 678]
4        5    [898, 589, 1162, 1889, 1181]
...    ...                             ...
6972  6973        [19, 700, 830, 1207, 24]
6973  6974    [664, 1135, 779, 1023, 1818]
6974  6975       [1162, 81, 369, 205, 664]
6975  6976    [1726, 1499, 1074, 873, 219]
6976  6977  [1521, 1562, 1799, 1456, 1883]

[6977 rows x 2 columns]

In [266]:
ans = ans[['q_id', 'web_id']]

In [268]:
ans.head(11)

    q_id  web_id
0      1    1567
1      1      16
2      1    1607
3      1    1704
4      1    1705
5      2    1615
6      2    1607
7      2      98
8      2    1904
9      2    1192
10     3     116

In [269]:
my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

/tmp/ipykernel_644854/3668412526.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

In [270]:
my_col

q_id
1        [1567, 16, 1607, 1704, 1705]
2        [1615, 1607, 98, 1904, 1192]
3        [116, 110, 1705, 1704, 1192]
4         [1632, 993, 1061, 223, 282]
5          [1639, 165, 470, 620, 926]
                    ...
6973       [1202, 410, 672, 1249, 97]
6974        [1675, 213, 89, 902, 165]
6975    [1608, 1607, 1677, 1592, 165]
6976    [1705, 1704, 903, 1887, 1886]
6977    [1636, 438, 1705, 1249, 1677]
Length: 6977, dtype: object

In [271]:
my_col = list(my_col)

In [274]:
my_col[0]

'[1567, 16, 1607, 1704, 1705]'

In [275]:
sample['web_list'] = my_col

In [276]:
sample.to_csv('my_sub_1.csv', index=False)

In [280]:
pd.read_csv('my_sub_1.csv').head()

   q_id                      web_list
0     1  [1567, 16, 1607, 1704, 1705]
1     2  [1615, 1607, 98, 1904, 1192]
2     3  [116, 110, 1705, 1704, 1192]
3     4   [1632, 993, 1061, 223, 282]
4     5    [1639, 165, 470, 620, 926]

In [281]:
pd.read_csv('my_sub_0.csv').head()

   q_id                      web_list
0     1    [1567, 16, 403, 672, 1249]
1     2   [1567, 1613, 1607, 672, 98]
2     3  [110, 1705, 1704, 1249, 116]
3     4   [1632, 223, 282, 1013, 248]
4     5    [165, 1639, 470, 620, 444]

In [ ]:
# egors bench

In [433]:
sample = pd.read_csv('../data/raw/sample_submission.csv')
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')
ans = ans[['q_id', 'web_id']]
my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)
my_col = list(my_col)
sample['web_list'] = my_col
sample.to_csv('my_sub_for_test.csv', index=False)

/tmp/ipykernel_644854/2220541734.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

In [434]:
sample

      q_id                        web_list
0        1     [132, 135, 837, 1567, 1490]
1        2    [372, 1705, 1704, 368, 1517]
2        3     [1761, 1752, 319, 54, 1704]
3        4    [1045, 1043, 1051, 380, 208]
4        5  [1615, 1548, 1561, 1564, 1489]
...    ...                             ...
6972  6973    [1902, 1552, 1040, 164, 716]
6973  6974   [368, 1907, 1627, 1905, 1071]
6974  6975    [692, 1705, 1704, 1157, 421]
6975  6976   [1072, 1655, 688, 1704, 1769]
6976  6977    [1636, 1304, 1924, 478, 438]

[6977 rows x 2 columns]

In [439]:
sample.to_csv('my_sub_7.csv', index=False)

In [438]:
sample.iloc[0].web_list

'[132, 135, 837, 1567, 1490]'

In [443]:
import pandas as pd
import ast

# === Загружаем CSV ===
ground_truth = pd.read_csv("../data/raw/top5.csv")           # размеченные web_id
predictions = pd.read_csv("my_sub_7.csv")  # предсказания RAG

def parse_web_list(s):
    """Парсим строку вида '[1, 2, 3]' в список чисел"""
    return ast.literal_eval(s) if isinstance(s, str) else []
ground_truth["web_list"] = ground_truth["web_list"].apply(parse_web_list)
predictions["web_list"] = predictions["web_list"].apply(parse_web_list)

#  Подсчёт Hit@K
K = 5
hits = []

for _, row in ground_truth.iterrows():
    qid = row["q_id"]
    true_ids = set(row["web_list"])

    # Проверяем, есть ли этот q_id в предсказаниях
    pred_row = predictions[predictions["q_id"] == qid]
    if pred_row.empty:
        continue

    pred_ids = set(pred_row.iloc[0]["web_list"][:K])

    # Hit@K = 1, если есть хотя бы одно совпадение
    hit = 1 if len(true_ids & pred_ids) > 0 else 0
    hits.append(hit)

# Средний результат
hit_at_k = sum(hits) / len(hits) if hits else 0
print(f"Hit@{K}: {hit_at_k:.4f}")

Hit@5: 0.6100