In [2]:
import pandas as pd

# Data Loading

In [3]:
questions = pd.read_csv('../data/raw/questions_clean.csv')

In [4]:
data = pd.read_csv('../data/raw/websites_updated.csv')

# Mini sample for test

In [5]:
questions.sample(200).to_csv('../data/raw/questions_clean_sample_200.csv')

In [6]:
data.sample(200).to_csv('../data/raw/websites_updated_sample_200.csv')

# EDA

In [7]:
data.head(3)

,web_id,url,kind,title,text
0,1,https://alfabank.ru/,html,"Альфа-Банк - кредитные и дебетовые карты, кред...",Рассчитайте выгоду\nРасчёт калькулятора предва...
1,2,https://alfabank.ru/a-club/,html,А-Клуб. Деньги имеют значение,Брокерские услуги\nОткрытие брокерского счёта ...
2,3,https://alfabank.ru/a-club/ultimate/,html,А-Клуб. Деньги имеют значение,Хотите получить больше информации?\nПозвоните ...

In [8]:
questions.head()

   q_id                                              query
0     1                                        Номер счета
1     2                              Где узнать бик и счёт
2     3  Мне не приходят коды для подтверждения данной ...
3     4  Оформила рассрочку ,но уведомлений никаких не ...
4     5  Здравствуйте, когда смогу пользоваться кредитн...

In [9]:
data.kind.value_counts()

kind
html        1802
document     135
Name: count, dtype: int64

In [10]:
data[data.kind=='document'].head(3)

,web_id,url,kind,title,text
33,34,https://alfabank.servicecdn.ru/site-upload/5e/...,document,zalog_general_terms.pdf,АКЦИОНЕРНОЕ ОБЩЕСТВО «АЛЬФА-БАНК» \n\n (дале...
1487,1488,https://alfabank.st/site-upload/38/95/1784/Ref...,document,Refin-pamyatka-08022024.pdf,"___ \n\n107078, МОСКВА \n\nУЛ. КАЛАНЧЕВСКАЯ, 2..."
1703,1704,https://alfabank.servicecdn.ru/site-upload/e3/...,document,dogovor_cbo_1082025.pdf,Приложение к Распоряжению АО «АЛЬФА-БАНК» \nот...

In [11]:
data.text.iloc[0]

'Рассчитайте выгоду\nРасчёт калькулятора предварительный. Персональные условия вы сможете узнать после оформления заявки\nПолучайте больше с Альфа-Банком\nСервисы\nКурсы валют\nВалюта | Покупка | Продажа |\n|---|---|---|\nДоллар США (USD) | 77 | 80,4 |\nЕвро (EUR) | 92 | 94,5 |\nКитайский юань (CNY) | 11,15 | 12,15 |\nБольше валют\nИнформация о курсах обмена иностранных валют является справочной и может меняться в течение дня. Точную информацию о курсах можно узнать в интернет-банке. Список отделений доступен по ссылке'

# Extracting importance columns

In [12]:
data_clean = data[['web_id', 'title', 'text']]

In [13]:
data_clean.head(3)

,web_id,title,text
0,1,"Альфа-Банк - кредитные и дебетовые карты, кред...",Рассчитайте выгоду\nРасчёт калькулятора предва...
1,2,А-Клуб. Деньги имеют значение,Брокерские услуги\nОткрытие брокерского счёта ...
2,3,А-Клуб. Деньги имеют значение,Хотите получить больше информации?\nПозвоните ...

# Answer checking

In [14]:
pd.set_option('display.max_colwidth', None)

In [18]:
ans.values

array([[1, 1, 1567, '1567_0',
        'Ещё нужен номер карты\nНомер карты\nНомер карты\nПродолжить',
        0.7004117243722217],
       [1, 2, 1769, '1769_117',
        'Номер телефонной справочной службы Банка 8 800 200 00 00, +7 495 788 88 78.',
        0.6421338613416023],
       [1, 3, 1795, '1795_115', 'счета  в  результате',
        0.4902309862858489],
       ...,
       [201, 3, 409, '409_4',
        'Можно ли заказать Альфа-Карту без гравировки?\nДа, вы можете оформить карту на сайте здесь.\nЕсли у меня уже есть Альфа-Карта, я могу перевыпустить её с гравировкой?\nПеревыпустить действующую Альфа-Карт',
        0.5810088335223437],
       [201, 4, 1748, '1748_2',
        'если карта потеряется\nКарту можно заблокировать или перевыпустить прямо в приложении\nЗаявка на Детскую карту\nЧто говорят родители\nпро Детскую карту\nЗачем я оформил карту ребёнку\nЕсли честно, у меня са',
        0.4337117939037411],
       [201, 5, 868, '868_2',
        'Заявка на Детскую карту\nЧто говорят родители\nпро Детскую карту\nЗачем я оформил карту ребёнку\nЕсли честно, у меня самого наличных денег особо и нет. Мне удобнее всё делать по карте. Если ему нужно — пр',
        0.4289298242429401]], shape=(1005, 6), dtype=object)

In [16]:
ans.head(10)

NameError: name 'ans' is not defined

In [17]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [19]:
for j, i in enumerate(ans.values):
    if j <= 1000:
        print('------НАЧАЛО-------')
        print('Question:')
        print(f'" { questions[questions.q_id == i[0]]['query']} "')
        print('Title of doc:')
        print(f'"{data[data.web_id == i[2]]['title']}"')
        print('Chunk from doc:')
        print(f'"{i[4]}"')
        #print(data[data.web_idк == i[1]]['text'])
        print(f'score : {i[5]}')
        print('-------КОНЕЦ--------')
        print()

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1566    Мобильный банк Альфа-Онлайн
Name: title, dtype: object"
Chunk from doc:
"Ещё нужен номер карты
Номер карты
Номер карты
Продолжить"
score : 0.7004117243722217
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1768    Visa_Prepaid_FIFA_Ring_PW.pdf
Name: title, dtype: object"
Chunk from doc:
"Номер телефонной справочной службы Банка 8 800 200 00 00, +7 495 788 88 78."
score : 0.6421338613416023
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1794    partner_cards_service_rules_v53.pdf
Name: title, dtype: object"
Chunk from doc:
"счета  в  результате"
score : 0.4902309862858489
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"1879    polit-obr-pers-dan.pdf
Name: title, dtype: object"
Chunk from doc:
"Фамилия, имя, отчество (при наличии),
фамилия, имя, отчество латинскими буквами
базовый номер, балансовые данные (номер
счета, остаток, валюта), дата рождения,
должность, идентификационный номер, "
score : 0.462325012249741
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 0    Номер счета
Name: query, dtype: object "
Title of doc:
"134    Платежные инструкции для расчетов по сделкам MM, FX — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Код валюты
Наименование банка
и адрес
Номер счета
Код СВИФТ
Белорусский рубль
Belarussian Ruble (BYN)
ЗАО «АЛЬФА-БАНК»
220013, Беларусь, г. Минск, ул. Сурганова, 43-47
BY66ALFA17020644300170270000
ALF"
score : 0.4377293163176141
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"371    Номер расчётного счёта: что это такое и расшифровка — Блог 🅰️ Альфа‑Банка
Name: title, dtype: object"
Chunk from doc:
"407 — счёт принадлежит юридическому лицу
02 — организация является коммерческой
810 — счёт открыт в рублях РФ
9 — контрольная цифра
0264 — код отделения кредитной организации. Чтобы узнать, в каком ба"
score : 0.7578615430427322
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"1041    Задолженность по кредитной карте — что будет если не платить
Name: title, dtype: object"
Chunk from doc:
"Есть несколько способов узнать информацию по вашей кредитной карте:
Интернет-приложение Альфа‑Онлайн. Здесь вы можете посмотреть выписку по счёту, узнать общую сумму долга, график платежей.
Мобильное "
score : 0.7554198181370368
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"1723    Оформите код самоинкассации
Name: title, dtype: object"
Chunk from doc:
"Как узнать, что деньги зачислены на счёт
Проверить зачисления можно через:
Интернет-банк
Мобильное приложение
Услугу Альфа‑Чек Бизнес
Контакт-центр
Запрос мини-выписки в банкомате
Как быстро сумма буд"
score : 0.6989312815505218
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"97    Дебетовая карта с кэшбэком в аптеках: оформите онлайн в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"Где я могу проверять информацию по услуге?
В мобильном приложении — Витрина — «Подключить бесплатные переводы». Внутри раздела можно посмотреть будет списана комиссия или нет, узнать дату списания и с"
score : 0.5652912078910586
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 1    Где узнать бик и счёт
Name: query, dtype: object "
Title of doc:
"96    Карта с кэшбэком в кафе и ресторанах: оформить онлайн в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"На какой платежной системе вы выдаете сейчас карты?
Все карты Альфа-Банка выпускаются на платежной системе Мир. Карты принимают на всей территории России и в некоторых странах за границей.
Где я могу "
score : 0.5246590945728486
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"115    Ваши деньги в безопасности
Name: title, dtype: object"
Chunk from doc:
"Я хочу, чтобы текущий пароль не менялся
Почему при подтверждении операции у меня не запросили секретный код?
Почему для подтверждения некоторых операций мне всё ещё приходят коды в смс?
Какие есть вид"
score : 0.9457088233427507
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1703    dogovor_cbo_1082025.pdf
Name: title, dtype: object"
Chunk from doc:
"Для осуществления данной операции Держатель вправе использовать только реквизиты Карты, выпущенной"
score : 0.7165384295285473
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"391    ИП или ООО для маркетплейса: что лучше выбрать и как открыть ООО для торговли на интернет-площадках — Блог 🅰️ Альфа‑Банка
Name: title, dtype: object"
Chunk from doc:
"Коды ОКВЭД — это уникальные наборы цифр, обозначающие определённые виды деятельности. Каждый такой набор может содержать от двух до шести цифр. Коды собраны в Общероссийском классификаторе видов эконо"
score : 0.420705725740982
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1760    ct-12-30052025.pdf
Name: title, dtype: object"
Chunk from doc:
"клиринга, установленный на дату обработки соответствующего подтверждения о совершении операции,
может  отличаться  от  соответствующего  курса,  установленного  на  момент  обработки  подтверждения
"
score : 0.3766746287356372
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 2    Мне не приходят коды для подтверждения данной операции
Name: query, dtype: object "
Title of doc:
"1759    ct-12-5062025.pdf
Name: title, dtype: object"
Chunk from doc:
"клиринга, установленный на дату обработки соответствующего подтверждения о совершении операции,
может  отличаться  от  соответствующего  курса,  установленного  на  момент  обработки  подтверждения
"
score : 0.3766746287356372
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1050    Как купить планшет в кредит онлайн без первоначального взноса 🅰️ | Альфа-Банк
Name: title, dtype: object"
Chunk from doc:
"На первый взгляд, это выгодно. Оформив рассрочку, покупатель оплачивает планшет кредитными деньгами, но погашает долг без процентов, поскольку магазины в период действия акции устанавливают скидку на "
score : 0.7899999999999999
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1761    dogovor_x5_5062025.pdf
Name: title, dtype: object"
Chunk from doc:
"телефона сотовой связи Клиента или (если Клиент подключил доставку уведомлений
через  Сервис  обмена  мгновенными  сообщениями)  в  виде  уведомлений  в
соответствующем  выбранном  Сервисе  обмена  "
score : 0.4773155343053051
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1757    dogovor_x5_30062025.pdf
Name: title, dtype: object"
Chunk from doc:
"телефона сотовой связи Клиента или (если Клиент подключил доставку уведомлений
через  Сервис  обмена  мгновенными  сообщениями)  в  виде  уведомлений  в
соответствующем  выбранном  Сервисе  обмена  "
score : 0.4773155343053051
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1042    Рассрочка по кредитной карте в Альфа-Банке: преимущества, как оформить — Блог Альфа⁠-⁠Банка
Name: title, dtype: object"
Chunk from doc:
"Можно ли отменить рассрочку Держателям кредитных карт доступна услуга моментального перевода выбранной суммы задолженности в рассрочку. По умолчанию клиентам предлагается перевести всю сумму задолженн"
score : 0.4609268089510409
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 3    Оформила рассрочку ,но уведомлений никаких не пришло
Name: query, dtype: object "
Title of doc:
"1760    ct-12-30052025.pdf
Name: title, dtype: object"
Chunk from doc:
"возможность  самостоятельно  управлять  настройками  Push-уведомлений  и  уведомлений  через
Сервис  обмена  мгновенными  сообщениями  по  доступным  категориям.  Управление  настройками
осуществляе"
score : 0.4457694596190374
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"1906    Перевыпуск дебетовой карты
Name: title, dtype: object"
Chunk from doc:
"Смогу ли я пользоваться картой, если закажу досрочный перевыпуск?
После регистрации банком заявки на досрочный перевыпуск старый пластик перестанет действовать.

Вы можете пользоваться цифровой копией"
score : 0.9424548569652756
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"925    Переводите деньги со счёта кредитки
Name: title, dtype: object"
Chunk from doc:
"Введите сумму.
Нажмите Перевести.
А какие условия?
А если я переведу деньги на кредитку по ошибке, смогу ли я их вернуть обратно?"
score : 0.6015085451463297
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"1534    В каких банках смогу снять наличные?
Name: title, dtype: object"
Chunk from doc:
"Общая информация
Мобильное приложение и Альфа-Онлайн
Комиссии по карте
Перевыпуск, блокировка и закрытие
Как перестать пользоваться картой?
Как пользоваться картой?
Начало использования
Всё про кэшбэк"
score : 0.4915515386443527
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"1040    Как работает кредитная карта: принцип работы кредитки
Name: title, dtype: object"
Chunk from doc:
"Благодаря возобновляемым кредитным линиям клиенты Альфа‑Банка годами (от 5 лет и более) пользуются деньгами и не платят проценты. По факту можно пользоваться кредиткой бессрочно. Банк не назначает как"
score : 0.4604383821188506
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 4    Здравствуйте, когда смогу пользоваться кредитной картой?
Name: query, dtype: object "
Title of doc:
"1658    Бивалютный депозит для ИП и малого бизнеса: тарифы от «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Начисленные проценты выплачиваются в любом случае и всегда в валюте размещения.
Застрахованы ли мои деньги на депозите?
Деньги ИП и компаний, которые внесены в реестр МСП, застрахованы в Агентстве по "
score : 0.4419054536880675
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"877    Дебетовая карта «Перекресток» - оформить банковскую карту «Перекресток» онлайн в Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"Баллы не начисляется за снятие наличных и комиссии банка по карте, списанные в соответствии с действующими тарифами"
score : 0.5735717910010005
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"675    Способы подключения
Name: title, dtype: object"
Chunk from doc:
"При любом способе эквайринга доступна оплата через СБП. На странице ввода данных карты отображается кнопка для оплаты по QR-коду, через который покупатель может оплатить покупку."
score : 0.5687434065837162
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"107    Рекомендации по переводам и платежам — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Отсутствие в платеже за патент значения ИНН клиента-мигранта ведет к проблемам с идентификацией платежа в ГИС ГМП и системах администраторов доходов бюджета, и в этом случае платеж за патент не считае"
score : 0.4985208155624494
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"137    Онлайн заявка на автокредит — оформить заявку на кредит на авто без посещения банка
Name: title, dtype: object"
Chunk from doc:
"На сайте Альфа-Банка есть специальный калькулятор, позволяющий просмотреть условия автокредитаперед тем, как подать заявку на получение денег. Можно выбрать срок и сумму займа, чтобы увидеть ежемесячн"
score : 0.4904538077621077
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 5    По истории платеж не отображается
Name: query, dtype: object "
Title of doc:
"211    Рефинансирование кредита в Екатеринбурге - оформить онлайн заявку на рефинансирование кредита в ЕКБ - «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Дополнительные финансы. При желании вы можете взять деньги не только для погашения текущих долгов, но и на другие цели.
Один платеж. Если вы рефинансируете сразу несколько займов, вам больше не нужно "
score : 0.4662836383169753
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1915    Как правильно закрыть банковскую карту
Name: title, dtype: object"
Chunk from doc:
"Можно ли закрыть карту дистанционно
Можно, если в вашем населённом пункте нет отделения банка, выпустившего пластик. Альфа⁠-⁠Банк закрывает банковские счета удалённо. Вы можете обратиться в Альфа⁠-⁠Ба"
score : 0.8287684015233219
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1905    Как закрыть счёт, к которому была привязана карта?
Name: title, dtype: object"
Chunk from doc:
"Как закрыть счёт, к которому была привязана карта?
Выберите его на главном экране приложения или Альфа-Онлайн: Действия → Закрыть счёт. Остаток на счёте можете перевести на другой счёт, отправить на м"
score : 0.8115709244511927
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"614    Ликвидация ИП или ООО — подготовка документов от 🅰️ Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"Как закрыть расчётный счёт после ликвидации бизнеса?
После того, как процесс ликвидации завершится, нужно подать заявление — только так расчётный счёт закроют. Это можно сделать через интернет-банк Ал"
score : 0.7184837984699828
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1935    Пополнение и вывод средств — Альфа-Инвестиции
Name: title, dtype: object"
Chunk from doc:
"Расписание:
- Собственные средства: T+1 ежедневно; T+0 (до 10 млн ₽) с 6:00 до 18:00 мск; перерывы 18:00–18:30, 20:00–20:30, 23:57–3:10.
- Заёмные средства: с 6:00 до 18:00 мск по будням (дни расчётов"
score : 0.6964211806173858
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 6    Здравствуйте, в рп. Нахабино отделение банка на улице Институская 00, можно закрыть бизнес счет?
Name: query, dtype: object "
Title of doc:
"1565    Инвестиции в драгоценные металлы в Альфа‑Банке
Name: title, dtype: object"
Chunk from doc:
"Понадобится всего несколько минут. Счёт откроется с базовым
Время покупки и продажи драгметаллов
Через приложение: онлайн 24/7 В отделениях: пн–чт: 10:00–17:15, пт: 10:00 — 16:00, сб-вс: выходной
Узна"
score : 0.6704641347592935
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"1703    dogovor_cbo_1082025.pdf
Name: title, dtype: object"
Chunk from doc:
"зарплатный

15"
score : 0.7838608348079582
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"1704    dogovor_cbo_1072025.pdf
Name: title, dtype: object"
Chunk from doc:
"зарплатный

15"
score : 0.7838608348079582
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"220    Может ли взять ипотеку самозанятый: условия — Блог 🅰️ Альфа‑Банка
Name: title, dtype: object"
Chunk from doc:
"Оформить в банке дебетовую карту для получения платы за работу от клиентов. Это дополнительный способ для банка убедиться в платёжеспособности клиента. С зарплатной картой список документов на ипотеку"
score : 0.4916287267476429
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"861    Телефонный центр «Альфа-Консультант» — «Альфа-Банк»
Name: title, dtype: object"
Chunk from doc:
"Узнать о задолженности и сумме минимального платежа
Частично или полностью погасить кредит
Заказать выдачу крупной суммы кредита наличными в отделении (только для отделений на территории Москвы и МО)
"
score : 0.2831688109527076
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 7    Узнать зарплатный счет
Name: query, dtype: object "
Title of doc:
"281    Статьи для крупного бизнеса и корпоративных клиентов 🅰️ Альфа-Банка
Name: title, dtype: object"
Chunk from doc:
"РКО
Кредиты
ВЭД
Факторинг
Зарплатный проект
РКО
Кредиты
ВЭД
Факторинг
Зарплатный проект
Всё для крупного бизнеса и корпоративных клиентов"
score : 0.2307103813666813
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"1024    Полезные статьи о кредитных картах 💳 | Альфа⁠-⁠Банк
Name: title, dtype: object"
Chunk from doc:
"в Альфа‑Онлайн: выберите счёт кредитной карты
запросив выписку в нашем офисе — комиссия за это зависит от вашего тарифа
с помощью уведомлений: откройте в приложении Настройки → Операции по картам, выб"
score : 0.7128652392104595
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"936    Оформить онлайн-заявку на кредитную карту — 🅰️ Заполнить заявку онлайн и получить кредитку в Альфа‑Банке
Name: title, dtype: object"
Chunk from doc:
"в Альфа‑Онлайн: выберите счёт кредитной карты
запросив выписку в нашем офисе — комиссия за это зависит от вашего тарифа
с помощью уведомлений: откройте в приложении Настройки → Операции по картам, выб"
score : 0.7128652392104595
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"158    💳 Кредитная карта Альфа-Банка. Оформить кредитку со льготным периодом 60 дней в 🅰️ Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"в Альфа‑Онлайн: выберите счёт кредитной карты
запросив выписку в нашем офисе — комиссия за это зависит от вашего тарифа
с помощью уведомлений: откройте в приложении Настройки → Операции по картам, выб"
score : 0.7128652392104595
-------КОНЕЦ--------

------НАЧАЛО-------
Question:
" 8    Подскажите, где я могу увидеть дату начала пользование кредитной карты?
Name: query, dtype: object "
Title of doc:
"920    💳 Кредитная карта Альфа-Банка. Оформить кредитку со льготным периодом 60 дней в 🅰️ Альфа-Банке
Name: title, dtype: object"
Chunk from doc:
"в Альфа‑Онлайн: выберите счёт кредитной карты

In [35]:
print(data[data.web_id == 579]['title'])

578    С 20 декабря 2024 года Альфа‑Банк изменяет ставки привлечения в валюте рубли по депозитам физических лиц: «Альфа‑Вклад. Новые деньги», «Альфа‑Вклад. Максимальный», «Альфа‑Вклад Пенсионный», «Альфа‑Вклад Пенсионный+» в российских рублях
Name: title, dtype: object

In [14]:
questions

      q_id                                              query
0        1                                        Номер счета
1        2                              Где узнать бик и счёт
2        3  Мне не приходят коды для подтверждения данной ...
3        4  Оформила рассрочку ,но уведомлений никаких не ...
4        5  Здравствуйте, когда смогу пользоваться кредитн...
...    ...                                                ...
6972  6973  Здравствуйте, оплатил вчера ЖКХ а кэшбек не на...
6973  6974  Здравствуйте,  можно ли заказать реквизиты бан...
6974  6975  Здравствуйте, подскажите пожалуйста где я могу...
6975  6976                  Реквизиты для оплаты номера карты
6976  6977  Можно ли отключить автопополнение брокерского ...

[6977 rows x 2 columns]

# Comparing with benchmark

In [108]:
bench = pd.read_csv('../data/processed/top5.csv', index_col=5)

In [109]:
bench = bench.drop(['0', '1', '2', '3', '4'], axis=1)

In [111]:
bench.head()

                                 lst
q_id
1       [1567, 1607, 496, 114, 1808]
2        [368, 599, 597, 1263, 1906]
3      [1175, 386, 1516, 1165, 1166]
4       [1043, 1620, 659, 1461, 478]
5     [1520, 1621, 1556, 1538, 1564]

In [115]:
bench.loc[5]

lst    [1520, 1621, 1556, 1538, 1564]
Name: 5, dtype: object

In [119]:
data[data.web_id==1564]

,web_id,url,kind,title,text
1563,1564,https://alfabank.ru/help/t/corp/debitcards/debetovaya-karta-aeroflot/,html,"Дебетовая карта Аэрофлот: все, что нужно знать","Общая информация\nМобильное приложение и Альфа-Онлайн\nКомиссии по карте\nПеревыпуск, блокировка и закрытие\nКак перестать пользоваться картой?\nКак пользоваться картой?\nНачало использования\nВсё про кэшбэк рублями\nСправки и выписки\nПрограмма “Деньги вам и друзьям”\nВсё про кэшбэк милями и баллами\nВсё о комиссиях и лимитах\nКэшбэк от партнёров\nИзготовление и доставка\nПлатежи и переводы"

In [144]:
list(map(int, bench.iloc[1].lst.replace(' ', '').replace('[', '').replace(']', '').split(',')))

[368, 599, 597, 1263, 1906]

In [ ]:
e

In [147]:
bench

                                 lst
q_id
1       [1567, 1607, 496, 114, 1808]
2        [368, 599, 597, 1263, 1906]
3      [1175, 386, 1516, 1165, 1166]
4       [1043, 1620, 659, 1461, 478]
5     [1520, 1621, 1556, 1538, 1564]
...                              ...
96       [1894, 123, 852, 886, 1749]
97       [1863, 1290, 90, 398, 1861]
98       [1916, 368, 1072, 326, 219]
99        [745, 704, 1734, 846, 706]
100     [1567, 114, 321, 1615, 1071]

[100 rows x 1 columns]

In [158]:
bench.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100],
      dtype='int64', name='q_id')

In [20]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [21]:
score = 0
for i in ans.values:
    if i[0] in bench.index:
        #print(i[0])
        #print(i[2])
        bench_line = list(map(int, bench.loc[i[0]].lst.replace(' ', '').replace('[', '').replace(']', '').split(',')))
        if i[2] in bench_line : score += 1
        #print(bench_line)
print(score / 100)

NameError: name 'bench' is not defined

In [297]:
ans = ans[['q_id', 'chunk_id']]

In [ ]:
import pandas as pd
import ast

# === Загружаем CSV ===
ground_truth = pd.read_csv("truth.csv")           # размеченные web_id
predictions = pd.read_csv("predictions_rag.csv")  # предсказания RAG

def parse_web_list(s):
    """Парсим строку вида '[1, 2, 3]' в список чисел"""
    return ast.literal_eval(s) if isinstance(s, str) else []

ground_truth["web_list"] = ground_truth["web_list"].apply(parse_web_list)
predictions["web_list"] = predictions["web_list"].apply(parse_web_list)

#  Подсчёт Hit@K
K = 5
hits = []

for _, row in ground_truth.iterrows():
    qid = row["q_id"]
    true_ids = set(row["web_list"])

    # Проверяем, есть ли этот q_id в предсказаниях
    pred_row = predictions[predictions["q_id"] == qid]
    if pred_row.empty:
        continue

    pred_ids = set(pred_row.iloc[0]["web_list"][:K])

    # Hit@K = 1, если есть хотя бы одно совпадение
    hit = 1 if len(true_ids & pred_ids) > 0 else 0
    hits.append(hit)

# Средний результат
hit_at_k = sum(hits) / len(hits) if hits else 0
print(f"Hit@{K}: {hit_at_k:.4f}")

# по каждому запросу
for idx, h in enumerate(hits):
    print(f"q_id={ground_truth.iloc[idx]['q_id']}: hit={h}")

# Загрузка решения

In [265]:
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')

In [255]:
sample = pd.read_csv('../data/raw/sample_submission.csv')

In [256]:
str([1, 23])

'[1, 23]'

In [257]:
sample

      q_id                        web_list
0        1     [935, 687, 963, 1893, 1885]
1        2    [1660, 1882, 1040, 1090, 64]
2        3      [1246, 698, 465, 757, 307]
3        4      [366, 1625, 461, 279, 678]
4        5    [898, 589, 1162, 1889, 1181]
...    ...                             ...
6972  6973        [19, 700, 830, 1207, 24]
6973  6974    [664, 1135, 779, 1023, 1818]
6974  6975       [1162, 81, 369, 205, 664]
6975  6976    [1726, 1499, 1074, 873, 219]
6976  6977  [1521, 1562, 1799, 1456, 1883]

[6977 rows x 2 columns]

In [266]:
ans = ans[['q_id', 'web_id']]

In [268]:
ans.head(11)

    q_id  web_id
0      1    1567
1      1      16
2      1    1607
3      1    1704
4      1    1705
5      2    1615
6      2    1607
7      2      98
8      2    1904
9      2    1192
10     3     116

In [269]:
my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

/tmp/ipykernel_644854/3668412526.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

In [270]:
my_col

q_id
1        [1567, 16, 1607, 1704, 1705]
2        [1615, 1607, 98, 1904, 1192]
3        [116, 110, 1705, 1704, 1192]
4         [1632, 993, 1061, 223, 282]
5          [1639, 165, 470, 620, 926]
                    ...
6973       [1202, 410, 672, 1249, 97]
6974        [1675, 213, 89, 902, 165]
6975    [1608, 1607, 1677, 1592, 165]
6976    [1705, 1704, 903, 1887, 1886]
6977    [1636, 438, 1705, 1249, 1677]
Length: 6977, dtype: object

In [271]:
my_col = list(my_col)

In [274]:
my_col[0]

'[1567, 16, 1607, 1704, 1705]'

In [275]:
sample['web_list'] = my_col

In [276]:
sample.to_csv('my_sub_1.csv', index=False)

In [280]:
pd.read_csv('my_sub_1.csv').head()

   q_id                      web_list
0     1  [1567, 16, 1607, 1704, 1705]
1     2  [1615, 1607, 98, 1904, 1192]
2     3  [116, 110, 1705, 1704, 1192]
3     4   [1632, 993, 1061, 223, 282]
4     5    [1639, 165, 470, 620, 926]

In [281]:
pd.read_csv('my_sub_0.csv').head()

   q_id                      web_list
0     1    [1567, 16, 403, 672, 1249]
1     2   [1567, 1613, 1607, 672, 98]
2     3  [110, 1705, 1704, 1249, 116]
3     4   [1632, 223, 282, 1013, 248]
4     5    [165, 1639, 470, 620, 444]

In [ ]:
# egors bench

In [186]:
# For full file
sample = pd.read_csv('../data/raw/sample_submission.csv')
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')
ans = ans[['q_id', 'web_id']]
my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)
my_col = list(my_col)
sample['web_list'] = my_col
sample.to_csv('my_sub_for_test.csv', index=False)

/tmp/ipykernel_494422/1682953711.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

In [175]:
# for 200 sample
# For full file
sample = pd.read_csv('../data/raw/sample_submission.csv').iloc[:201]
ans = pd.read_csv('../data/processed/questions_top5_web_ids_with_chunks.csv')
ans = ans[['q_id', 'web_id']]
my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)
my_col = list(my_col)
sample['web_list'] = my_col
sample.to_csv('my_sub_for_test.csv', index=False)

/tmp/ipykernel_494422/3921890783.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  my_col = pd.Series(ans.groupby('q_id').apply(lambda x: list(x.web_id))).apply(str)

In [149]:
sample.web_list = sample.web_list.apply(lambda x: x.replace('.0', ''))
sample.to_csv('my_sub_for_test.csv', index=False)

In [180]:
pd.read_csv('my_sub_for_test.csv')

      q_id                        web_list
0        1     [135, 1567, 1880, 114, 108]
1        2      [368, 372, 862, 455, 1570]
2        3   [1175, 1704, 1705, 386, 1758]
3        4  [1043, 1704, 1705, 1761, 1760]
4        5   [926, 1620, 1520, 1518, 1561]
...    ...                             ...
6972  6973     [1902, 716, 216, 171, 1219]
6973  6974   [1627, 372, 1905, 1071, 1527]
6974  6975    [1705, 543, 1915, 408, 1704]
6975  6976   [1704, 1705, 1761, 1760, 903]
6976  6977     [432, 403, 1924, 438, 1080]

[6977 rows x 2 columns]

In [189]:
sample.to_csv('my_sub_15.csv', index=False)

In [190]:
sample.iloc[0].web_list

'[1769, 1567, 1795, 16, 1705]'

In [188]:
sample

      q_id                        web_list
0        1    [1769, 1567, 1795, 16, 1705]
1        2         [1042, 372, 97, 96, 89]
2        3    [116, 1704, 1536, 1147, 310]
3        4     [1051, 1061, 223, 408, 350]
4        5    [1907, 926, 1202, 410, 1746]
...    ...                             ...
6972  6973       [1746, 102, 60, 165, 175]
6973  6974   [1527, 773, 1676, 1298, 1299]
6974  6975         [98, 1014, 97, 96, 692]
6975  6976  [1072, 1761, 1704, 1775, 1752]
6976  6977    [1636, 432, 438, 1924, 1935]

[6977 rows x 2 columns]

In [187]:
import pandas as pd
import ast

# === Загружаем CSV ===
ground_truth = pd.read_csv("../data/raw/top5_updated.csv")           # размеченные web_id
predictions = pd.read_csv("my_sub_for_test.csv")  # предсказания RAG

def parse_web_list(s):
    """Парсим строку вида '[1, 2, 3]' в список чисел"""
    return ast.literal_eval(s) if isinstance(s, str) else []
ground_truth["web_list"] = ground_truth["web_list"].apply(parse_web_list)
predictions["web_list"] = predictions["web_list"].apply(parse_web_list)

#  Подсчёт Hit@K
K = 5
hits = []

for _, row in ground_truth.iterrows():
    qid = row["q_id"]
    true_ids = set(row["web_list"])

    # Проверяем, есть ли этот q_id в предсказаниях
    pred_row = predictions[predictions["q_id"] == qid]
    if pred_row.empty:
        continue

    pred_ids = set(pred_row.iloc[0]["web_list"][:K])

    # Hit@K = 1, если есть хотя бы одно совпадение
    hit = 1 if len(true_ids & pred_ids) > 0 else 0
    hits.append(hit)

# Средний результат
hit_at_k = sum(hits) / len(hits) if hits else 0
print(f"Hit@{K}: {hit_at_k:.4f}")

Hit@5: 0.0400

p

In [ ]:
sample = sample.drop('')

In [185]:
bad = []
for i, s in enumerate(predictions["web_list"]):
    try:
        ast.literal_eval(str(s))
    except Exception:
        bad.append((i, s))

bad

[(816, '[1704.0, 1705.0, 1712.0, 558.0, nan]'),
 (2066, '[1704.0, 1705.0, 1761.0, 1758.0, nan]'),
 (4397, '[863.0, 1747.0, 865.0, 314.0, nan]'),
 (4408, '[1747.0, 865.0, 863.0, 314.0, nan]'),
 (4422, '[865.0, 863.0, 1747.0, 314.0, nan]')]

In [146]:
sample = sample.drop([134])

KeyError: '[134] not found in axis'

In [147]:
sample

     q_id                        web_list
0       1  [1157, 1704, 1705, 1567, 1880]
1       2     [1157, 372, 368, 1098, 862]
2       3   [116, 1915, 1705, 1760, 1758]
3       4   [478, 1915, 1038, 1924, 1043]
4       5      [921, 1026, 920, 163, 166]
..    ...                             ...
196   197    [1704, 739, 1158, 1825, 372]
197   198     [926, 1758, 1704, 79, 1619]
198   199    [1929, 865, 1747, 1704, 863]
199   200  [1705, 1761, 1704, 1760, 1758]
200   201    [1033, 1704, 938, 921, 1025]

[200 rows x 2 columns]